---
title: "SADs neutras"
author: "Mori, Danilo"
date: "19/11/2022"
output: 
  html_document:
    toc: true
    toc_depth: 5
editor_options: 
  chunk_output_type: console
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,eval = FALSE,message = FALSE,warning = FALSE)
# pacotes
library(twosamples)
library(sads)
library(doMC)
library(gridExtra)
library(ggplot2)
library(readr)
library(purrr)
library(stringr)
library(tidyr)
library(insight)
library(bbmle)
library(DHARMa)
library(lme4)
library(plyr)
library(dplyr)
# dados
# df_p
df_p <- read_csv("dados/df_p.csv")
# df_sim
df_sim <- read_csv("dados/df_simulacao.csv") |> 
  select(-tif.path) |> 
  inner_join(y=mutate(
    data.frame(txt.path = list.files(path="dados/simulacao",pattern=".txt")),
    SiteCode = str_extract(txt.path,".*?(?=.txt)")),
    by="SiteCode")
# df_Urep
df_Urep <- read_csv("dados/csv/df_Urep.csv")
df_U <- df_Urep |> 
  drop_na() |> 
  pivot_longer(cols = `1`:`10`,names_to = "n",values_to = "U") |> 
  group_by(SiteCode,k) |> 
  summarise(Umed = mean(U)) |> 
  inner_join(x=select(df_sim,SiteCode, k, d,txt.path),by=c("SiteCode","k"))
# df_SADrep
df_SADrep <- mutate(data.frame(
  SADrep.path = list.files(path = "dados/csv/SADs_neutras/MNEE",
                           pattern = ".csv",full.names = T)),
  SADobs.path = gsub("neutras/MNEE","observadas",SADrep.path),
  SiteCode = str_extract(SADrep.path,"(?<=EE\\/).*?(?=.csv)"))
# df_repMNEE
df_repMNEE <- read_csv("dados/csv/resultados_MN/MNEE/df_repMNEE")
# df_resultMNEE
df_resultMNEE <- read_csv("dados/csv/resultados_MN/MNEE/df_resultMNEE.csv")
# funções
source("source/dinamica_coalescente.R")
source("source/2samples_testes.R")
```

# MNEE

## Simulação das SADs por sítio de amostragem

```{r MNEE simulação das SADs por sítio de amostragem e k}
setwd("dados/simulacao/")
f_sadMNEE <- function(df, n_replicas=100){
  land_path <- df$txt.path[1]
  f_simCoalescente <- function(X){
    dinamica_coalescente(U = X$Umed, S=0, disp_range = X$d, N_simul=n_replicas,landscape = land_path)
  }
  m_SADreplicas <- adply(df,1,f_simCoalescente)
  write_csv(select(m_SADreplicas,-(txt.path:Umed)),
            file = paste0("../csv/SADs_neutras/MNEE/",df$SiteCode[1],".csv"))
}
registerDoMC(3)
d_ply(df_U,"SiteCode",f_sadMNEE,.parallel = TRUE)
```

## Comparação com a SAD observada

### Resultados gerais testes KS, DTS e a contagem de espécies

```{r testes KS DTS e S}
registerDoMC(3)
df_repMNEE <- adply(df_SADrep,1,f_resultsMN,.parallel = TRUE)
write_csv(select(df_repMNEE,SiteCode:S), file = "dados/csv/resultados_MN/MNEE/df_repMNEE")
```

```{r summarise resultados de MNEE para df_resultMNEE}
df_resultMNEE <- df_repMNEE |> 
  group_by(SiteCode,k) |> 
  summarise(nCongKS = sum(p.KS>0.05),
            nCongDTS = sum(p.DTS>0.05),
            Smed = mean(S),
            Ssd = sd(S),
            Smin = min(S),
            Smax = max(S))
df_resultMNEE <- df_resultMNEE |> 
  inner_join(x=df_p,by="SiteCode")
write_csv(df_resultMNEE,file = "dados/csv/resultados_MN/MNEE/df_resultMNEE.csv")
```

### Comparação SAD acumulada e predita


```{r comparação SAD acumulada e predita}
df_plot <- inner_join(df_resultMNEE,df_SADrep,by="SiteCode") |> 
  left_join(y=distinct(select(df_sim,SiteCode:S_obs)),by="SiteCode")
# df <- df_plot |> filter(SiteCode == "BAjuss")
f_plot.SADacumulada <- function(df,parallel=TRUE,repo="dados/csv/resultados_MN/MNEE/png_SADsAcumuladas/"){
  # dados
  m_SADrep <- read_csv(df$SADrep.path[1])
  m_SADrep$k <- factor(m_SADrep$k,levels=unique(m_SADrep$k))
  df_SADobs <- read_csv(df$SADobs.path[1])
  # subfunção
  f_SAD <- function(X){
    v_SADrep <- unname(sort(table(as.matrix(X[,-(1:2)])),decreasing = T))
    cbind(X[,1:2],v_SADrep)
  }
  # rotina
  registerDoMC(3)
  df_return <- rename(adply(m_SADrep,1,f_SAD,.expand = F,.parallel = parallel),n=X1,sp.name=Var1)
  # labels
  v_labels <- c(paste0("k=",round(df$k,2),
                       "; KS=",df$nCongKS,
                       "; DTS=",df$nCongDTS,
                       "; <Srep>=",round(df$Smed,2)))
  names(v_labels) <- df$k
  v_title = paste0(df$SiteCode[1],
                   ", p=",round(df$p[1],2),
                   ", plot=",df$effort_ha[1],"ha",
                   ", Ntotal=",df$Ntotal[1],
                   ", Sobs=",df$S_obs[1])
  # gráfico
  p <- ggplot(df_return,aes(x=Freq)) +
    stat_ecdf(alpha=0.4,aes(group=n)) +
    facet_wrap(~k,ncol=5,labeller = as_labeller(v_labels)) +
    stat_ecdf(data=df_SADobs,aes(x=N),color="red") +
    coord_cartesian(xlim = range(df_SADobs$N),expand = FALSE) +
    scale_x_continuous(breaks=seq(min(df_SADobs$N),max(df_SADobs$N),by=10)) +
    labs(y="",x="indivíduos",
         title=v_title) +
    theme_minimal()
  png(paste0(repo,df$SiteCode[1],".png"),width = 11.04, height = 5.864,units="in",res=500)
  print(p)
  dev.off()
}
f_plot.SADacumulada(filter(df_plot,SiteCode=="BAjuss"))

d_ply(df_plot,"SiteCode",f_plot.SADacumulada)
```



