---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
# pacotes
library(trackdown)
# both overwrite: 
# overwrite the current google drive file with the current Rmd:
# upload_file(file="secoes_texto/introducao/introducao.Rmd",
#             gpath="mestrado/artigo_principal/secoes_texto/",
#             hide_code=TRUE)
update_file(file ="secoes_texto/introducao/introducao.Rmd",
            gpath = "mestrado/artigo_principal/secoes_texto/",
            hide_code = TRUE)
# overwrite the current Rmd with the current google drive 
download_file(file ="relatorio_final.Rmd",
              gpath = "mestrado/disciplinas/BIE5716/")
```



Não existe consenso sobre a relação entre a perda de cobertura florestal e a biodiversidade de árvores presente na cobertura florestal remanescente (@fletcher2018habitat,@fahrig2019habitatA,@miller2019does,@valente2023toward), apesar da elevada extensão da perda de área natural (@diaz2019pervasive). Existem dois programas de pesquisa em ecologia de paisagens que possuem concepções distintas de como investigar essa relação (@miller2019does,@valente2023toward). O programa de pesquisa padronista pressupõe que é necessário investigar a associação entre a biodiversidade local e o padrão de cobertura florestal remanescente na paisagem ao redor (@fahrig2003effects, @fahrig2019habitatB, @arroyo2020designing, @valente2023toward). Dentro dessa perspectiva, o padrão de cobertura florestal remanescente é medido em dois aspectos: quantidade (ou proporção) de cobertura florestal remanescente (p); e alguma métrica de complexidade espacial da cobertura florestal remanescente controlado por p, chamado de fragmentação per se (@fahrig2003effects, @fahrig2017ecological, @fahrig2019habitatB). Não há consenso sobre a métrica adequada de fragmentação per se ou em qual escala espacial da paisagem ao redor deve ser feita essa medida (@valente2023toward). As síntese de evidências feitas nessa perspectiva concluem que o efeito da fragmentação per se é pequeno em relação ao efeito de p e em geral é positivo (@fahrig2003effects, @fahrig2017ecological). O programa de pesquisa processista pressupõe que é necessário investigar a associação entre a biodiversidade remanescente e o processo de mudança de cobertura vegetal (@didham2012rethinking). Dessa perspectiva, há aqueles que compreendem não ser possível ou adequado mensurar fragmentação per se, e sim apenas fragmentação, o efeito conjunto da perda de cobertura e da mudança na configuração espacial da cobertura remanescente (@didham2012rethinking, @haddad2015habitat, fletcher2023landscapeB). Outros compreendem que a estimativa de efeito de fragmentação per se pressupondo independência do efeito de p é enviesada por não considerar o efeito indireto de p no efeito de fragmentação per se (@didham2012rethinking, @fletcher2018habitat, @puttker2020indirect). A síntese de evidência dentro dessa última perspectiva concluem que o efeito da fragmentação per se é negativo e não apresenta menor magnitude do que o efeito de p (@puttker2020indirect). Outros consideram que, uma vez que a escala de investigação não é determinada em função da escala dos mecanismos que influenciam a resposta ecológica em estudo, as análises que investigam o efeito de fragmentação per se não são interpretáveis (@fletcher2018habitat, @fletcher2023addressingA).  Esse debate entre os dois principais programas de pesquisa em ecologia de paisagens pode influenciar as estratégias de design e priorização de áreas para a conservação e restauração dos ecossistemas naturais (@banks2021suggestion, @arroyo2021preserving,@miller2019does,@valente2023toward).

# Questão de Escala
Um dos desafios da conciliação entre os programas de pesquisa é que a relação entre biodiversidade e cobertura florestal remanescente pode ser compreendido em múltiplas dimensões de escala espaço-temporal @mcgill2015fifteen, (@jackson2015ecologists, @fletcher2023addressingA). Quando a investigação utiliza padrões de biodiversidade observados em momento único é comum considerar dois tipos de escalas temporais: de longo prazo e de curto prazo (@kuussaari2009extinction, @lira2019temporal, @figueiredo2019understanding). Os efeitos de curto prazo têm sido aproximados pela situação da biodiversidade no cenário de ausência de perda de cobertura florestal, ou seja, a perda de cobertura é apenas a subtração de parte da biodiversidade original nessa situação prístina (@kuussaari2009extinction, @may2019geometry, @fahrig2022resolving). Os efeitos de longo prazo são aproximados pela situação de um novo equilíbrio da biodiversidade remanescente na situação da cobertura florestal remanescente contemporânea ao evento de amostragem (@kuussaari2009extinction,@thompson2019characterising). Essas duas situações podem ser usadas como referências para estimar o atraso na resposta da biodiversidade à mudança na cobertura florestal (@kuussaari2009extinction, @lira2019temporal, @figueiredo2019understanding). A escala espacial em geral é compreendida em três dimensões: dos mecanismos; da observação do fenômeno (e.g. o tamanho da parcela); e da análise das possíveis preditoras do fenômeno (@fletcher2023addressingA). Diversos mecanismos têm sido sugeridos como importantes para compreender a relação entre biodiversidade e cobertura florestal remanescente (@fletcher2018habitat,@fahrig2019habitatA), porém, a conectividade, i.e., a movimentação dos indivíduos na cobertura florestal remanescente, é considerada fundamental em ambos programas de pesquisa (@Villard2014, @fahrig2013rethinking, @fletcher2018negative, @fahrig2022resolving), pois, sob total limitação de dispersão espera-se que os únicos mecanismos relevantes sejam locais, sem precisar explicitar a paisagem ao redor (@chase2020biodiversity). Portanto, é necessário investigar a dispersão quando se determina a escala de análise (@arroyo2020designing,@fletcher2023addressingA). 

# Proposta de conciliação
Nós propomos um caminho de conciliação dos programas de pesquisa de ecologia de paisagens pelo uso do programa de pesquisa da teoria neutra da biodiversidade local. O programa de pesquisa da teoria neutra se baseia em explorar os pressupostos auxiliares ao de equivalência funcional na construção de modelos populacionais que simulam a dinâmica de nascimentos e mortes dos indivíduos no espaço (@rosindell2012case, @munoz2016neutral,@bausman2019aims). Ao pressupor equivalência funcional (situação em que todas as espécies apresentam as mesmas taxas demográficas per capita) é possível construir modelos com poucos parâmetros (@azaele2016statistical), onde é possível ajustar a capacidade de dispersão dos indivíduos remanescentes (@munoz2016neutral), dessa forma, explicitando um mecanismo essencial para compreender a escala do fenômeno e da análise. Uma classe de modelos neutros se baseia em teoria coalescente que explicitamente considera a escala da observação na simulação das dinâmicas populacionais (@rosindell2008coalescence, @azaele2016statistical). Esses modelos neutros coalescente são utilizados para investigar a situação de efeitos imediatos e de longo prazo (@chisholm2018species, @thompson2019characterising). Além disso, há consenso de que modelos neutros podem ser aproximações suficientes para descrever métricas de biodiversidade local de árvores observada em momento único como a riqueza de espécies e abundância (@azaele2016statistical), métricas de biodiversidade utilizada em revisões de ambos programas de pesquisa (@puttker2020indirect, @fahrig2017ecological). A teoria neutra possibilita explorar as hipóteses mínimas dos programas de pesquisa em ecologia de paisagens em um arcabouço teórico comum, permitindo a comparação direta de múltiplas hipóteses, característica necessária para conciliação teórica entre os programas de pesquisa (@valente2023toward).  Além disso, há uma longa literatura que apresenta formas de integrar os modelos neutros com modelos mais complexos que consideram os componentes adaptativos da biodiversidade (@leroi2020neutral). Para adequar os pressupostos do programa de pesquisa da teoria neutra vamos explorar características comuns dos argumentos de ambos programas de pesquisa em ecologia de paisagens.

## Características comuns dos argumentos de cada programa de pesquisa
Ambos programas de pesquisa em ecologia de paisagens utilizam revisões das evidências com características comuns (@puttker2020indirect, @fahrig2017ecological, @watling2020support, @riva2022disproportionately). Esses estudos são feitos a partir de bases de dados que agregam trabalhos de inventários da biodiversidade, em que as características dos locais de amostragem são revisadas da literatura e as características da paisagem são obtidas de ferramentas de sensoriamento remoto (@puttker2020indirect, @riva2022disproportionately). A riqueza e abundância local de espécies observadas em um único momento são utilizadas como métricas de biodiversidade (@puttker2020indirect, @fahrig2017ecological, @watling2020support). Em estudos com espécies árboreas a escala de observação costuma ser a parcela (@puttker2020indirect, @fahrig2017ecological, @watling2020support). A escala de análise foi determinada por uma análise chamada escala de efeito (@puttker2020indirect, @fahrig2013rethinking), onde a extensão espacial da paisagem escolhida é aquela que maximiza a relação entre preditoras e métrica de biodiversidade local observada (@jackson2015ecologists). Existe um pressuposto na análise de escala de efeito de que as características observadas na paisagem apresentam algum efeito importante na métrica de biodiversidade em estudo (@frazier2017landscape). Esse pressuposto é explorado de diversas formas nas hipóteses mínimas de cada programa de pesquisa.
Entre os padronistas, esse pressuposto é explorado de duas formas. Primeiro, a afirmação de que é suficiente desconsiderar a fragmentação per se como descritor da biodiversidade local, uma vez que o efeito de p é muito maior em magnitude (@fahrig2017ecological), pressupõe um efeito de longo prazo. Segundo, quando propõe que a fragmentação per se apresenta efeito positivo por maximizar a amostragem espacial da cobertura florestal remanescente, e portanto da biodiversidade remanescente, pressupõe efeito de curto prazo (@fahrig2022resolving). Os processistas pressupõem efeito de longo prazo quando afirmam que o efeito de fragmentação per se, principalmente relacionado com a proporção de área de borda, é negativo e elevado, uma vez que a análise considera a possibilidade de interdependência entre as métricas (@puttker2020indirect). 
Em ambos programas de pesquisa as hipóteses mínimas podem ser aproximadas por dinâmicas ecológicas idealizadas de um modelo neutro. A hipótese mínima de que apenas o efeito de curto prazo é relevante pode ser aproximada pela simulação do equilíbrio em uma paisagem sem perda de habitat (paisagem hipotética prístina) (@chisholm2018species, @may2019geometry). A hipótese de que a fragmentação per se é irrelevante em comparação ao efeito de perda de habitat pode ser aproximada pela simulação de equilíbrio em uma paisagem em que a cobertura florestal remanescente está aglomerado ao redor da parcela (paisagem hipotética aglomerada) (@valente2023toward). A hipótese de que a fragmentação per se é relevante, uma vez que explicitado a interdependência das métricas de p e fragmentação per se (@puttker2020indirect), pode ser aproximada pela simulação de equilíbrio na particular configuração espacial da cobertura florestal remanescente (paisagem hipotética contemporânea (@thompson2019characterising).

## relação entre escala de análise e escala do mecanismo do fenômeno no modelo neutro
        Um importante aspecto de trabalhar com modelos neutros é a parametrização do modelo. Os modelos neutros são conhecidos por apresentarem boa congruência com os padrões empíricos de biodiversidade local de árvores, uma vez que seus parâmetros são ajustados a partir dos padrões a serem avaliados (@gotelli2006null, @rosindell2012case,@leroi2020neutral) . Indicando que é necessário ter cautela sobre os valores de parâmetros quando comparações são feitas e na interpretação desses parâmetros livres (@gotelli2006null, @etienne2011spatial, @azaele2016statistical). Uma vez que a capacidade de dispersão for controlada para investigar a escala do fenômeno e da análise, o outro parâmetro disponível é a taxa de entrada de novas espécies no sistema (taxa U) (@thompson2020pycoalescence). A taxa U pode ser interpretada como especiação ou reposição do banco de propágulos, uma vez que, sob equilíbrio, ela compensa a perda de espécies por deriva ecologica (a perda de espécies devido a flutuação aleatória do número de indivíduos em cada espécie, @azaele2016statistical REFs classícas). Se a taxa U for ajustada para que o modelo aproxime bem a riqueza local de espécies em um particular nível de capacidade dispersão dos indivíduos, a taxa U pode ser interpretado como o complementar da conectividade simulada entre a paisagem ao redor e a parcela amostrada necessária para manter a riqueza local (@may2012dispersal). Sob essa interpretação, a taxa U pode ser usada para investigar a escala da conectividade potencial simulada e dessa forma determinar a escala de análise adequada para os níveis de dispersão simulados (apêndice Efeito de Escalar). Outra possibilidade é criar preditoras a partir da comparação par a par entre a taxa U estimada entre paisagens hipotéticas. Por exemplo, a métrica de fragmentação per se pode ser obtido pela diferença na taxa U estimada pela paisagem contemporânea e aglomerada, dessa forma, a escala de análise é coerente com a escala do mecanismo.

# Expectativa
        Uma vez que é determinada a escala de análise que é coerente com a escala do mecanismo é possível estabelecer algumas expectativas sobre o efeito da área ao redor da parcela (paisagem local) na manutenção da diversidade local. O predito nas paisagens hipotéticas contemporânea e aglomerada pode divergir do predito na paisagem prístina com o aumento da perda de cobertura florestal. O predito na paisagem contemporânea pode começar a divergir em áreas com menor perda de cobertura florestal do que o predito na paisagem aglomerada se a parcela amostrada estiver próxima da região de borda (REF) e a limitação de dispersão for severa (REF), ou seja, mesmo em paisagens acima do limiar de percolação (situação em que a maior parte da cobertura florestal remanescente está estruturalmente conectada, Swift et al. 2010; Taubert et al. 2018). Abaixo do limiar de percolação, em paisagens com proporção intermediária, há a maior variabilidade na possível configuração espacial da cobertura remanescente e espera-se que elementos de conexão (e.g. corredores ecológicos e stepping stones) possam possibilitar a conectividade entre manchas de cobertura florestal com potencial de manter populações viáveis (@Villard2014). Assim, em paisagens com proporção  intermediárias espera-se observar a maior potencial diferença entre as paisagens contemporâneas e aglomeradas. Em paisagens com pouca cobertura florestal espera-se que as manchas remanescentes estejam pouco isoladas ou com pouca capacidade de manter populações viáveis (@Pardini2010, @Villard2014, Hanski 2015), nessas situações, esperamos a maior diferença entre o predito na paisagem prístina e o predito nas paisagens contemporânea e aglomerada. Nós esperamos que as métricas funcionais de efeito da paisagem ao redor, baseadas na diferença entre taxa U estimada nas paisagens hipotéticas, sejam preditoras adequadas para descrever a divergência do predito nas paisagens hipotéticas.

# Objetivo
        Nosso objetivo é aproximar as hipóteses mínimas de cada programa de pesquisa no arcabouço teórico comum da teoria neutra da biodiversidade usando um modelo neutro espacialmente explícito. Para isso selecionamos, de uma base de dados com características similares às utilizadas em revisões de ambos programas de pesquisa, inventários florestais realizados na Floresta Atlântica adequados para serem aproximados pelo modelo neutro espacialmente explícito. Determinarmos a extensão da paisagem ao redor investigando a situação de ausência de perda de cobertura florestal a fim de encontrar aquela extensão espacial que é suficiente para que a simulação da diversidade local seja restringida apenas pela limitação de dispersão simulada (apêndice Efeito de Escalar). Simulamos graus de limitação de dispersão dos indivíduos em três tipos de paisagens hipotéticas: contemporânea, com a configuração espacial observada no mesmo ano do inventário florestal; aglomerada, com a proporção de cobertura florestal contemporânea aglomerada ao redor da parcela amostrada; prístina, situação idealizada em que toda a paisagem está preenchida com cobertura florestal. Estimamos as taxas U necessárias para aproximar a riqueza de espécies local observada em cada paisagem hipotética e graus de limitação de dispersão. Simulamos a distribuição de abundância de espécies (SAD) a partir da taxa U livre para aproximar a riqueza local observada em cada respectiva paisagem hipotética e a partir da taxa U livre na paisagem prístina. Avaliamos a congruência entre as SADs simuladas e a SAD empírica. Os contrastes entre as taxas U estimadas entre pares de paisagens hipotéticas foram utilizados como métrica de efeito da paisagem ao redor (de perda de cobertura florestal, de fragmentação per se, e de fragmentação total). 



################### antigo

# Opening versão 2:

O debate entre os dois principais programas de pesquisa em ecologia de paisagens questiona a relevância do espaço para compreender os efeitos da perda de habitat na manutenção da biodiversidade local (REF). Conclusões sobre a relevância do espaço podem influenciar o design ou priorização de paisagens para a conservação e restauração dos ecossistemas naturais (REFs dos dois programas de pesquisa). O programa que pressupõe independência dos efeitos da perda de habitat e da configuração espacial, controlado pela quantidade de habitat - chamado de fragmentação per se, conclui que os efeitos da fragmentação per se são pequenos e em geral positivos (REFs). Dentro dessa perspectiva, uma hipótese mínima é que é suficiente desconsiderar o espaço para descrever a biodiversidade local da cobertura florestal em função da chegada de propágulos vindos da paisagem ao redor




os efeitos do isolamento estrutural, i.e. a redução da chegada de propágulos vindos da paisagem ao redor ou o aumento da substituição de coespecíficos devido à particular configuração espacial do habitat remanescente, para compreender os efeitos majoritários da perda de habitat na manutenção da diversidade local (Fahrig 2013, REFs). O programa que pressupõe interdependência entre os efeitos da perda de habitat e as concomitantes mudanças na configuração espacial não reconhece essas conclusões que pressupõem independência a priori entre quantidade de habitat e a chamada fragmentação per se (REF). Um desafio de investigar os efeitos da perda de habitat e da fragmentação per se é associação estatística entre as métricas dessas variáveis nos sistemas naturais e a dependência da escala de observação da paisagem (REF). 

Alternativamente à decomposição ortogonal da configuração espacial do habitat remanescente em quantidade de habitat e fragmentação per se, é possível avaliar a necessidade de considerar a configuração espacial do habitat em comparação ao considerar apenas a quantidade de habitat remanescente na paisagem, sem o isolamento estrutural do habitat da parcela na paisagem (REF). Essa abordagem sugere o uso de modelos ecológicos que pressupõem explicitamente a configuração espacial do habitat em relação a quantidade de habitat na dinâmica ecológica que resulta no padrão de diversidade local observado. Para modelar a biodiversidade local é necessário pressupor a dispersão de indivíduos da paisagem ao redor (@Hubbell_2011, @Chase_2020, @Aavik_2017). Os modelos que pressupõe apenas a quantidade de habitat não incluem a influência do espaço na conectividade (REF), a movimentação de indivíduos no habitat remanescente na paisagem ao redor (REF). Os modelos que consideram a configuração espacial podem simular a interação entre a limitação de dispersão dos indivíduos e a particular configuração espacial da paisagem na conectividade (Campos et al. 2011, 2012, Thompson et al. 2019). 

A influência da configuração espacial na conectividade pode depender dos requerimentos de habitat e capacidade de dispersão da espécie, e da proporção de cobertura vegetal na paisagem ao redor (@Villard2014). Quando multiplas espécies são modeladas uma expectativa é que a configuração espacial do habitat poderá ser necessária para descrever a diversidade local ao longo de todo gradiente de cobertura vegetal (REF hanskis, @Pardini2010, @Villard2014); contudo, a variabilidade da configuração espacial aumenta em proporções intermediárias de habitat, onde corredores ecológicos ou stepping stones podem contribuir com a conectividade de manchas de habitat com capacidade de manter populações viáveis (@Villard2014).[a] Assim, uma expectativa é que a necessidade de pressupor configuração espacial do habitat pode mudar em função da cobertura vegetal e grau de limitação de dispersão. Essa expectativa se baseia em modelos que investigam a resposta ecológica em situação de equilíbrio na heterogeneidade da paisagem (REF). Tradicionalmente a ecologia de paisagens investiga a relação entre resposta ecológica observada e heterogeneidade contemporânea da paisagem (FRAZIER ET AL 2017), mas há reconhecimento de que não considerar a conectividade espaço-temporal pode negligenciar boa parte da conectividade de um local (@Martensen2017). A avaliação da conectividade espaço-temporal para taxóns que podem apresentar grande atraso na resposta ecológica é um campo aberto no conhecimento (REF), pois a duração da trajetória detalhada da heterogeneidade da paisagem é inferior ao tempo esperado de atraso (REF), e.g. na Floresta Atlântica há 35 anos de mapas detalhados (REF) e comunidades de árvores podem ter atrasos na ordem de centenas de anos (REF). Nesse contexto, alguns autores sugerem uma abordagem alternativa à tradicional de aproximar a paisagem ao redor pela situação de ausência de perda de habitat na reconstrução da diversidade biológica (Fahrig et al. 2022). Modelos de equilíbrio que contrastam a situação de ausência de perda de habitat (e.g. Chisholm et al. 2018, May et al. 2019) e a configuração contemporânea da paisagem (e.g. Campos et al. 2011, 2012, Thompson et al. 2019) podem estimar a amplitude do atraso na resposta ecológica esperada naquela paisagem (Thompson et al. 2018), e servir de referência para construção de modelos que incorporarem a conectividade espaço-temporal (REF, INCLUIR Gilbert et al. 2006 e a relação com teoria neutra). 

Outro desafio é a determinação da paisagem local. 
-FALAR SOBRE A RELACAO CAPACIDADE DE DISPERSÃO E EXTENSAO ESPACIAL DA PAISAGEM.
Os modelos que pressupõe apenas a quantidade de habitat requerem a delimitação adequada da paisagem ao redor, aquela área que pode fornecer a maior parte dos propágulos para a parcela amostrada (REF). Os modelos que pressupõe a configuração espacial do habitat requerem uma extensão espacial mínima suficiente para que a dinâmica ecológica seja restringida apenas pela limitação de dispersão dos indivíduos (REF).
Uma abordagem comum é a análise de escala de efeito que determina a extensão espacial da paisagem que máxima a associação estatística entre um padrão de diversidade local e uma métrica da heterogeneidade da paisagem ao redor (REF). 
Essa análise pressupõe equilíbrio entre heterogeneidade contemporânea da paisagem local e o padrão de diversidade local. 




# Introdução

  Para predizer a biodiversidade local (glossário) é necessário considerar a dispersão de indivíduos da paisagem ao redor (@Hubbell_2011, @Chase_2020, @Aavik_2017), porém não há consenso sobre como modelar esse processo (@Miller_Rushing_2019, @Fahrig_2019, @Fletcher_2018). A dinâmica ecológica (glossário) que influencia a abundância local pode ocorrer com taxas demográficas mais lentas do que as taxas de modificação da heterogeneidade da paisagem (@Figueiredo2019, @Lira2019, @Rosa2021). Detalhes da trajetória da heterogeneidade da paisagem (@Ben-Hur2020) e da biodiversidade associada( são escassos (@Rosa2021, @Daskalova2020). Uma abordagem é investigar os dados estáticos de biodiversidade e do mapa de cobertura vegetal da paisagem ao redor (@Frazier2017). Nesses casos, sítios onde é esperado observar populações sob influência da heterogeneidade da paisagem (e.g. grandes áreas de floresta contíguas ou paisagens com alguma informação histórica disponível) são amostrados (e.g. @Pardini2010, @Banks-Leite2014, @Watling_2020, @Puttker2020, @Rocha-Santos2020). Trabalhos empíricos que usam esse tipo de abordagem podem dialogar com modelos teóricos que consideram equilíbrio das populações na heterogeneidade da paisagem (@Hanski2011, @Villard2014). A situação de equilíbrio é modelada como aquela em que não há tendência de redução ou aumento na biodiversidade local (@Figueiredo2019, @Lira2019, @Storch_2019). Em biomas com grande dinamismo, como a Floresta Atlântica, a configuração espacial da cobertura vegetal na paisagem pode ter mudado ao longo do tempo (@Rosa2021), e a configuração espacial contemporânea pode aproximar mal a influência da geometria da cobertura vegetal na movimentação dos indivíduos ao longo do tempo (@Martensen2017). Se há balanço nulo de perda e ganho de habitat, apenas mudança na configuração espacial, uma primeira aproximação é pressupor ausência da influência da distância entre fragmentos, assim para descrever a biodiversidade local seria suficiente considerar apenas a quantidade de cobertura vegetal remanescente na paisagem (@Fahrig_2013). Por outro lado, quando há incerteza no histórico da região ou se o desmatamento é recente, uma alternativa é pressupor que não há relação da heterogeneidade contemporânea da paisagem e a biodiversidade local (@fahrig2022resolving), o equilíbrio pode ter sido atingido anteriormente, em uma paisagem idealizada com pouca influência da perda de habitat (@May2019), uma vez que o atraso na resposta ecológica pode levar centenas de anos para alguns táxons em certos contextos (@Figueiredo2019, @Lira2019).

  Os trabalhos teóricos que pressupõem equilíbrio sugerem que uma variável chave é a proporção de cobertura vegetal na paisagem, pois ao passo que se perde cobertura vegetal e a paisagem passa o limiar de percolação, os fragmentos remanescentes podem se tornar menores e mais isolados, populações perdidas localmente podem não ser repostas enquanto outras podem aumentar em abundância relativa; com a redução do habitat para proporções abaixo de níveis intermediários há também a redução do número de fragmentos possíveis, levando à perda de espécies que estavam restritas aos fragmentos perdidos (@Pardini2010, @Villard2014). Além disso, a redução no habitat disponível aumenta o risco de extinção local e mesmo populações especialistas podem se extinguir em condições favoráveis, devido a estocasticidade demográfica (@Thompson2017). Em proporções intermediárias de habitat na paisagem há maior variação na possível configuração espacial do habitat e maior chance de corredores ecológicos ou stepping stones contribuírem com o aumento da movimentação de indivíduos de fragmentos com capacidade de manter populações viáveis (@Pardini2010, @Villard2014). Se a situação de equilíbrio na configuração espacial contemporânea for uma boa aproximação e a particular configuração espacial restringir a movimentação dos indivíduos sob limitação de dispersão, então pode não ser suficiente pressupor apenas a quantidade de habitat remanescente na paisagem (@Hanski_2015,@Fahrig_2013) ou aproximar a diversidade local pela situação idealizada de equilíbrio em paisagem sem perda de habitat (@fahrig2022resolving). Uma expectativa é que possa ser melhor pressupor a configuração espacial contemporânea em comparação com pressupor apenas a quantidade de habitat quando a paisagem apresentar proporção intermediária de habitat, pelo menos em cenários de limitação de dispersão mais severos. Quanto mais branda a limitação de dispersão mais similar deve ser a qualidade da predição de um modelo que pressupõe a configuração espacial ou apenas a quantidade de habitat (@Shem-Tov2017). A diferença na qualidade da predição de modelos que pressupõe a configuração espacial contemporânea ou idealizada sem perda de habitat deve aumentar quanto maior a perda de habitat, e deve ser mais acentuado abaixo de proporções intermediárias de habitat.

  Aqui avaliamos 6 modelos baseados em indivíduos que pressupõem equilíbrio para predizer a distribuição de abundância de espécies (SAD) de árvores da Floresta Atlântica, uma ecorregião que vem perdendo e ganhando cobertura vegetal com diferentes taxas há mais de 500 anos, resultando em cobertura remanescente inferior à 20% e paisagens ao longo de um gradiente de cobertura vegetal (@joly2014experiences, @Rosa2021). Os mapas de cobertura vegetal mais detalhados iniciam em 1985 (@Rosa2021). Selecionamos trabalhos da base de dados TreeCo (@Lima2015) realizados a partir de 1986, que amostraram pelo menos 1 ha de área contígua (parcela) e identificaram indivíduos arbóreos de pelo menos 5 cm de DBH. Usamos a teoria neutra da biodiversidade (@Hubbell_2011) para construir modelos coalescentes baseados em indivíduos que compartilham pressupostos mas diferem em como conceitualizam a dispersão dos indivíduos entre a parcela e a paisagem. Nos modelos neutros, o equilíbrio ocorre quando o número de espécies perdidas pela competição neutra por espaço (deriva ecológica) é balanceado pela constante e aleatória colonização de novas espécies na paisagem por evento de nascimento (taxa de especiação; @Azaele2016). Os modelos neutros podem ser organizados de duas maneiras: tipo da paisagem (contemporânea e idealizada) e dinâmica de substituições (espacialmente explícito, espacialmente implícito e sem espaço). Os modelos espacialmente explícitos pressupõem que a substituição de indivíduos depende da distância e posição dos indivíduos na paisagem, a limitação à dispersão impõe que a probabilidade de substituição diminui com a distância (@Thompson2020). Os modelos sem espaço pressupõem que a capacidade de dispersão é infinita em relação ao tamanho da paisagem, todos os propágulos da paisagem tem igual probabilidade de substituir qualquer morte (@Shem-Tov2017). Os modelos espacialmente implícitos enfatizam o possível isolamento entre parcela e paisagem ao redor, a probabilidade de substituição de um indivíduo da parcela depende apenas se o propagulo é de um índivíduo da parcela ou se é imigrante da paisagem ao redor, a probabilidade de um imigrante colonizar a parcela aumenta com a redução da limitação de dispersão (@Etienne2011). Para os modelos que consideram o espaço implícito ou explícito, simulamos 20 cenários de limitação de dispersão por sítio de amostragem, onde a proporção de propágulos que permanece até a vizinhança imediata da árvore progenitora variou de 0.99 até 0.05. Para os 6 modelos estimamos a taxa de especiação necessária para obter a riqueza de espécies na SAD observada e então simulamos 100 SADs réplicas para cada combinação de parâmetros (mapa de cobertura vegetal da paisagem, cenário de limitação de dispersão se for o caso). 

<!-- (- A ecologia de paisagens trabalha com o pressuposto de que a heterogeneidade da paisagem observada no momento (o padrão) está relacionado com a resposta ecológica (pressupostos de contemporaneidade). [REPENSAR ]   ) -->

<!-- ##### Fim da proposta 1 -->

<!-- versão anterior: -->

<!-- de modo que  -->
<!-- Aqui investigamos o efeito de pressupor equilíbrio na paisagem contemporânea em comparação ao equilíbrio em uma paisagem idealizada íntegra e o de pressupor a configuração espacial da cobertura vegetal em comparação com apenas a quantidade de cobertura vegetal na construção de modelos para descrever a diversidade local de árvores e a sua relação com a paisagem ao redor. Procuramos predizer a distribuição de abundância de espécies (SAD) observada em inventários florestais que amostraram parcelas de Floresta Atlântica, uma ecorregião que vem perdendo e ganhando cobertura vegetal com diferentes taxas há mais de 500 anos, resultando em uma cobertura remanescente total inferior à 20% e paisagens ao longo de um gradiente de cobertura vegetal (PESQUISAR MAIS REF). Os mapas de cobertura vegetal mais detalhados iniciam em 1985 (Rosa et al. 2021), anterior a essa data a informação disponível é limitada e variável entre regiões (PESQUISAR MAIS REF). Usamos a teoria neutra da biodiversidade para construir 4 modelos baseados em indivíduos que compartilham pressupostos mas diferem em como conceitualizam a dispersão dos indivíduos entre a parcela e a paisagem. Nos modelos neutros, o equilíbrio ocorre quando o número de espécies perdidas pela competição neutra por espaço (deriva ecológica) é balanceado pela constante colonização de novas espécies na paisagem. Interpretamos os modelos neutros que pressupõem a quantidade de cobertura vegetal (espacialmente implícito) como uma simplificação dos modelos que consideram a configuração espacial da cobertura vegetal remanescente (espacialmente explícito) e simulamos cenários de limitação à dispersão variando a proporção de propágulos que permanecem na vizinhança imediata da progenitora até a ausência de limitação de dispersão per capita. -->

<!-- Introdução -->
<!-- - A conservação e restauração dos ecossistemas naturais tem grande potencial para mitigar ou reverter as crises em andamento da perda de biodiversidade, mudanças climáticas, e de seguridade alimentar. -->
<!-- - Para conservação ou restaurar é preciso considerar a perspectiva da paisagem, ou seja, mesmo para manter pequenos fragmentos florestais, por exemplo, é necessário considerar a área ao redor da área de interesse, pois estas áreas podem contribuir com propágulos repondo espécies extintas localmente ou modificando a abundância relativa das espécies presentes. -->
<!-- - Um dos desafios de conservação e restaurar é a falta de consenso sobre os princípios da relação entre a diversidade local e a perda de habitat na paisagem.  -->
<!-- - O habitat pode ser aproximado pela de área do ecossistema de interesse. -->
<!-- - O funcionamento dos ecossistemas naturais depende da diversidade biológica associado ao ecossistema. -->
<!-- - Um programa de pesquisa pressupõe independência dos efeitos da perda de habitat e da mudança na configuração espacial do habitat remanescente (fragmentação per se); a partir dessa perspectiva, uma hipótese mínima foi que a diversidade biológica em uma área amostral aumenta com a quantidade de habitat na paisagem (hipótese da quantidade de habitat). -->
<!-- - Outro programa de pesquisa pressupõe interdependência dos efeitos da perda de habitat e da fragmentação per se, assim não é possível pressupor a priori independência desses efeitos; uma hipótese mínima desse programa é que a configuração espacial do habitat remanescente na paisagem, resultado da perda de habitat e do particular padrão espacial de fragmentação per se, pode ser necessário para descrever a diversidade biológica em uma área amostral. -->
<!-- - Essas hipóteses mínimas não foram testadas em um arcabouço comum e independente dos pressupostos centrais dos dois programas de pesquisa. -->
<!-- Opening -->




<!-- A perda de área de ecossistemas florestais (habitat) pela expansão da área de atividade humana não tradicional (matriz) coloca em risco a manutenção da diversidade biológica associada a estes ecossistemas. A concomitante redução da área disponível para as populações naturais e mudança na configuração espacial do habitat remanescente, potencialmente restringindo a movimentação dos indivíduos no habitat, aumentam o risco de perda de espécies (REF; Fahrig 2003, 2019; Pardini et al. 2018; REF).  -->
<!-- - As observações e experimentações realizadas para compreender a perda de habitat na diversidade biológica dos ecossistemas florestais ocorrem em geral na escala local ou do fragmento florestal (REF, RAFLima et al.; Haddad et al. 2015).  -->
<!-- Mas para compreender a manutenção das populações naturais na escala local é necessário considerar a relação dos processos ecológicos locais e aqueles na área ao redor (paisagem, REF Metzger et al.). A paisagem ao redor pode contribuir com propágulos para a dinâmica local, repondo espécies localmente extintas (efeito resgate) ou modificar a abundância relativa das espécies (efeito de massa) (Ricklefs 1988; Aavki et al. 2018; Watling et al. 2020; Thompson et al. 2017).  -->
<!-- - Relacionar  -->
<!-- Não há consenso sobre os princípios gerais sobre a relação entre a perda de habitat na escala da paisagem e a manutenção das populações naturais na escala local (Fletcher Jr et al. 2018; Fahrig et al. 2019; Miller-Rushing et al. 2019). Parte do motivo para   -->

<!-- A perda de habitat pode ser compreendida em múltiplas escalas (McGill et al. 2015) e ao passo que a pesquisa sobre a relação da biodiversidade e funcionamento de ecossistemas procura scaling up as conclusões obtidas na escala local (Gonzales et al. 2020), não há uma escala espacial ótima para pesquisar a perda de habitat (McGill et al. 2015).  -->
<!-- Porém para compreender a manutenção das populações naturais na escala local é necessário considerar a relação entre processos locais e aqueles ocorrendo na área ao redor (paisagem, REF Metzger et al.). A paisagem ao redor pode contribuir com propágulos para a dinâmica local, repondo espécies localmente extintas (efeito resgate) ou aumentar a abundância relativa de algumas espécies (efeito de massa) (Ricklefs 1988; Aavki et al. 2018; Watling et al. 2020; Thompson et al. 2017).  -->
<!-- No entanto, não há consenso sobre os princípios da relação entre a perda de habitat na escala da paisagem e a manutenção das populações naturais na escala local (Fletcher Jr et al. 2018; Fahrig et al. 2019; Miller-Rushing et al. 2019). -->

<!-- # Qual a ideia central? -->
<!-- “(...) não há consenso sobre os princípios da relação entre a perda de habitat na escala da paisagem e a manutenção das populações naturais na escala local (Fletcher Jr et al. 2018; Fahrig et al. 2019; Miller-Rushing et al. 2019).” -->
<!-- - eu quero que as pessoas leiam esse parágrafo e i) tenha entendido a importância e contexto geral do problema do artigo; e ii) entenda que irei estudar sobre os princípios sobre a relação entre a perda de habitat na escala da paisagem e manutenção das populações na escala local. -->

<!-- # Elementos Necessários: -->
<!-- - A conservação e restauração dos ecossistemas naturais têm potencial de mitigar ou reverter as crises em andamento de perda de biodiversidade, de mudanças climáticas, e seguridade alimentar (REF). -->
<!-- - Para conservar ou restaurar mesmo que pequenas áreas de floresta, por exemplo, é necessário considerar a paisagem ao redor, pois estas áreas podem contribuir com propágulos para a área de interesse, repondo espécies extintas localmente ou influenciando a abundância das espécies presentes (REF). -->
<!-- Hipóteses mínimas de cada grupo de pesquisa -->
<!-- Não há consenso sobre os princípios da relação entre a perda de habitat na escala da paisagem e a manutenção das populações naturais na escala local (Fletcher Jr et al. 2018; Fahrig et al. 2019; Miller-Rushing et al. 2019). Um programa de pesquisa pressupõe que os efeitos na diversidade biológica da perda de habitat e da mudança na configuração espacial são independentes (fragmentação per se, Fahrig 2003; Fahrig et al. 2019). Revisões de trabalhos empíricos que seguem essa abordagem indicam que o efeito da mudança da configuração espacial independente da perda de habitat não é significativo ou é idiossincrático, podendo inclusive ser positivo (Fahrig 2017, 2020; mas veja Fletcher Jr. et al. 2018a; e Fahrig et al. 2019). Dessa perspectiva, uma hipótese mínima é que a diversidade biológica local aumenta com a quantidade de habitat na paisagem (hipótese da quantidade de habitat; Fahrig 2013). A hipótese da quantidade de habitat pressupõe que o efeito de área per se, i.e. toda área de habitat é uma amostra bem misturada do pool de espécies disponível, é suficiente para descrever a diversidade local (Fahrig 2013; Watling et al. 2020). Um programa de pesquisa concorrente desafia esta abordagem ao pressupor que pode existir interdependência entre a perda de habitat e o padrão de fragmentação per se: a perda de habitat é o principal processo causando as mudanças na configuração espacial do habitat remanescente e portanto não é possível separar ortogonalmente os dois efeitos a priori (Didham, Kapos & Ewers 2012; Fletcher Jr et al. 2018a; Püttker et al. 2020). Além disso, baseado em experimentos na escala do fragmento florestal e em trabalhos teóricos na escala da paisagem, espera-se que a configuração espacial do habitat remanescente na paisagem seja um importante determinante das populações por restringir a movimentação dos indivíduos no habitat remanescente (Villard & Metzger 2014; Hanski 2015; Haddad et al. 2015, 2017a). Assim, uma outra hipótese mínima é que a configuração espacial do habitat remanescente, resultado da perda de habitat e do padrão de fragmentação per se, é necessária para descrever a diversidade biológica local observada em paisagens fragmentadas (hipótese da configuração espacial de hábitat; Villard & Metzger 2014, Hanski 2015). Essas hipóteses mínimas não foram testadas em um arcabouço comum e independente dos pressupostos centrais de cada programa de pesquisa. -->
<!-- Expectativa teórica: a configuração deve restringir a conectividade em paisagens com proporção intermediária de habitat -->
<!-- A hipótese mínima que melhor descreve a diversidade biológica observada em uma área amostral deve depender da proporção de habitat remanescente na paisagem local e das características das espécies em estudo. Uma expectativa é que a configuração espacial do habitat remanescente é pressuposto importante para descrever a diversidade biológica local em paisagens onde a particular configuração espacial do habitat pode restringir a conectividade (Villard & Metzger 2014). A conectividade, movimentação dos indivíduos no habitat remanescente, depende da geometria do habitat e da capacidade de dispersão dos indivíduos (Brudvig 2016; Levine & Murrell 2003; Taubert et al. 2018; Villard & Metzger 2014). Em proporções muito baixas todo o habitat remanescente deve está aglomerado no fragmento florestal de estudo (Hanski 2015). Acima do limiar de percolação a maior parte do habitat na paisagem está bem conectado e pouco isolado (Swift et al. 2010; Taubert et al. 2018). Em proporções intermediárias há maior variação no possível padrão de configuração espacial do habitat e maior chance de corredores ecológicos ou stepping stones contribuírem para o aumento da conectividade entre fragmentos com capacidade de manter populações viáveis (Villard & Metzger 2014). Indivíduos com capacidade de se dispersar para além da vizinhança imediata da planta progenitora podem acessar habitat separado pela matriz em função da configuração espacial do habitat remanescente (Baguette et al. 2013; Cote et al. 2017). Apesar de existirem algumas espécies que apresentam aumento na capacidade de dispersão per capita após evento de perda de habitat (e.g. Bacles  et al. 2006), as espécies nativas que dependem de agentes dispersores específicos têm sua capacidade de dispersão reduzida pela modificação do serviço de dispersão (e.g. defaunação) em paisagens fragmentadas (Harrison et al. 2013; Pardini et al. 2018; REF). Sob severa limitação à dispersão, a movimentação dos indivíduos é possível apenas se o habitat estiver diretamente conectado.  -->
<!-- Abordagem -->
<!-- Um desafio em testar as hipóteses mínimas com dados observacionais é a típica correlação entre a quantidade de habitat na paisagem e métricas que descrevem a complexidade da forma da configuração em paisagens não experimentais (Fahrig 2003; Ewers & Didham 2006). Uma possível abordagem é utilizar modelos teóricos para aproximar as hipóteses mínimas (Hanski 2015). Modelos são idealizações dos sistemas naturais que geram predições baseadas apenas em seus pressupostos (Connolly et al. 2017; Travassos-Brito et al. 2021). A congruência entre predição e padrão observado permite avaliar como os pressupostos e suas relações descrevem os sistemas naturais (Connolly et al. 2017; REF). Uma forma de avaliar as hipóteses mínimas em um arcabouço comum é aproximá-las por modelos que considerem a réplica da configuração espacial do habitat remanescente em contraste ao considerar apenas a quantidade de habitat remanescente sem estrutura espacial (Hanski 2015; REF). O uso de modelos teóricos que consideram a movimentação dos indivíduos entre a área amostral e paisagem ao redor permite modelar o efeito de massa e resgate promovido pela paisagem (Thompson et al. 2017; REF). Uma primeira aproximação para descrever a movimentação dos indivíduos é por uma função de dispersão comum a todos os indivíduos (REF). A função de dispersão descreve a probabilidade de colonização pela distância entre progenitor e habitat vago e a capacidade de dispersão per capita (REF). Quando a estrutura espacial não é considerada, uma simplificação é modelar a movimentação dos indivíduos como a probabilidade média de indivíduos da paisagem ao redor colonizarem a área amostral segundo a função de dispersão (Chisholm & Lichstein 2009). A Teoria Neutra da Biodiversidade (Hubbell 2001) oferece um ponto de partida parcimonioso para construir modelos de dinâmica ecológica que podem modelar a contribuição de propágulos da paisagem ao redor na área amostral (efeito de massa e resgate) e considerar diferentes paisagens hipotéticas com e sem estrutura espacial (Prevedello et al. 2016; REF). -->
<!-- Paisagem local e métrica de diversidade local -->
<!-- Outro desafio em testar as hipóteses mínimas é determinar qual a extensão espacial da paisagem local adequada para investigar o padrão de diversidade biológica considerado (REF). A extensão espacial da paisagem local determina quais as áreas podem fornecer propágulos para a área amostral e, dado a configuração espacial do habitat na região, a proporção de cobertura vegetal na paisagem (Fahrig 2021 Reply to Santiago). A extensão espacial da paisagem local também deve estar relacionada com o padrão observado de forma não trivial (REF). Em outros trabalhos que avaliaram as hipóteses mínimas por modelos estatísticos, a diversidade local foi aproximada por métricas relacionadas com o número de espécies controlado pelo esforço amostral (e.g. Püttker et al. 2020; Watling et al. 2020). Essas mesmas variáveis foram usadas para determinar a extensão espacial da paisagem por uma análise de escala de efeito (Püttker et al. 2020; Watling et al. 2020). A análise de escala de efeito determina uma única extensão espacial que maximiza a relação entre proporção de habitat na paisagem e a variável que descreve a diversidade local (Jackson & Fahrig 2015). Controlado pela densidade de indivíduos e extensão espacial, a proporção de habitat é igual à quantidade de habitat remanescente. Portanto, um possível problema em usar a análise de escala de efeito com a variável de interesse é selecionar a extensão espacial onde a hipótese da quantidade de habitat deve ter bom suporte a priori. Uma outra abordagem é utilizar um padrão de diversidade biológica como variável resposta que seja relacionada com a variável usada na análise de escala de efeito. Por exemplo, para um mesmo número de espécies e número de indivíduos (uma métrica de esforço amostral) há diversas formas que os indivíduos podem se distribuir em cada espécie (REF Eco Letters 2013).  -->
<!-- Objetivo -->

<!-- Aqui nós aproximamos as hipóteses mínimas por modelos neutros que consideram ou a configuração espacial da paisagem e modelam a movimentação dos indivíduos por uma função de dispersão (modelo neutro espacialmente explícito) ou apenas a quantidade de habitat na paisagem e modelam a movimentação como a probabilidade média de um indivíduo da paisagem colonizar a área amostral (modelo neutro espacialmente implícito). Usamos a distribuição de abundância de espécies de árvores adultas (SAD) observada em áreas amostrais contíguas na Floresta Atlântica (Lima et al. 2015) como padrão de diversidade biológica local. Determinamos a extensão espacial da paisagem local pela análise de escala de efeito (Jackson & Fahrig 2015) com o número de espécies controlado pelo número de indivíduos amostrados como variável de interesse. As variáveis usadas na análise de efeito de escala foram usadas para parametrizar os modelos neutros (Figura 3). Pressupomos que a cobertura vegetal é uma aproximação da disponibilidade de habitat para árvores adultas (but see Brudvig et al. 2017, Pardini et al. 2018; Chazdon et al. 2016 REF). Usamos os mapas de cobertura vegetal do LandSat 8 (Hansen et al. 2013) como uma aproximação da configuração espacial da cobertura vegetal no momento da amostragem da SAD. Selecionamos inventários florestais distribuídos ao longo de um gradiente de cobertura vegetal natural (Figura 1). Nós avaliamos as condições de proporção de cobertura vegetal na paisagem local e limitação de dispersão per capita onde o modelo neutro espacialmente explícito oferece uma aproximação melhor do que o modelo neutro espacialmente implícito (Figura 2). Nossos resultados mostraram que o modelo espacialmente explícito apresenta melhor ajuste em mais condições do que esperado se a configuração espacial do habitat é pressuposto necessário para descrever a diversidade local apenas se a proporção de cobertura vegetal é intermediária e a capacidade de dispersão severamente limitada (Villard & Metzger 2014; Püttker et al. 2020; Watling et al. 2020).  -->

[a]pois, em paisagens acima do limiar de percolação, todo o habitat está estruturalmente  conectado; quando a proporção de cobertura vegetal é baixa além da redução do tamanho das manchas e aumento do isolamento delas, há também redução no número de manchas, levando à extinção de espécies endêmicas.
