---
title: "Reunião 16 de maio 2023"
author: "Mori, Danilo"
output: 
  html_document:
    toc: true
    toc_depth: 5
editor_options: 
  chunk_output_type: console
---


```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = FALSE,eval = TRUE,message = FALSE,warning = FALSE)
# pacotes
library(gratia)
library(doMC)
library(gridExtra)
library(metR)
library(ggplot2)
library(readr)
library(stringr)
library(tidyr)
library(insight)
library(bbmle)
library(DHARMa)
library(mgcv)
library(lme4)
library(plyr)
library(dplyr)
source("source/nameModel.R")
source("source/f_PredIntGAMM.R")
# objetos
# load("dados/Rdata/md_MNEE.Rdata")
# load("dados/Rdata/l_md_GAMM.Rdata")
# dados
load("dados/Rdata/l_md.contrastes.Rdata")
# df_p
df_p <- read_csv("dados/df_p.csv")
# df_resultMNEE
df_resultados <- read_csv("dados/csv/resultados_MN/df_resultados.csv")
# df_sim
df_sim <- read_csv("dados/df_simulacao.csv")
# df_ad
f_z <- function(x) (x-mean(x))/sd(x)
df_ad <- inner_join(x=distinct(select(df_resultados,-(Ssd:Smax))),
                    y=distinct(select(df_sim,-tif.path)),
                    by=c("SiteCode","k"),multiple="all") |>
  # escolhi remover depois do ajuste, para obter um melhor ajuste e depois excluir os valores
  # filter(k > 0.20) |> # figuras 5 e 6 apêndice Efeito de Escala
  mutate(k_cont = round(k,2),
         across(Ntotal:S_obs,log,.names="log_{.col}"),
         log_S.N = log_S_obs - log_Ntotal,
         across(c(p,k_cont,log_Ntotal:log_S.N),f_z,.names = "{.col}_z")) |>
  select(-c(effort_ha, Ntotal:S_obs))
# df_md
df_md <- df_ad |> 
  mutate(SiteCode = factor(SiteCode))
# df_newdata
df_newpred <- read_csv(file="dados/csv/df_newpred.csv") |> 
  select(-starts_with("log_")) |> 
  rename(k_z = k_cont_z)
# df_pred
# df_pred <- read_csv("dados/csv/resultados_MN/MNEE/df_pred.csv")
# df_newdat <- expand.grid(p_z = seq(min(df_ad$p_z),max(df_ad$p_z), length=150),
#                          k_cont_z = seq(min(df_ad$k_cont_z),max(df_ad$k_cont_z), length=150))
# df_newdat <- adply(df_newdat,1,.fun = \(x) cbind(x,distinct(select(df_ad,SiteCode,log_S_obs_z,log_Ntotal_z))))
# write_csv(df_newdat,"dados/csv/df_newdataSADs.csv")
df_contrastes <- read_csv(file="dados/csv/taxaU/df_contrastes.csv") |> 
  inner_join(df_sim |> select(SiteCode,Ntotal:S_obs) |> distinct(),
             by="SiteCode") |> 
  rename(N=Ntotal,S=S_obs) |> 
  mutate(across(N:S,log,.names="log.{.col}"),
         across(c(p,k,log.N:log.S),f_z,.names = "{.col}_z"),
         SiteCode = factor(SiteCode)) |> 
  select(-c(N:log.S))
# df_intPred
df_intPred <- read_csv("dados/csv/df_intePred_contrastes.csv")
```

# Contrastes

```{r GE contrastes e possíveis preditoras}
df_contrastes |> 
  pivot_longer(cols = k:p,names_to = "pred_class",values_to = "pred_values") |> 
  mutate(pred_class = factor(pred_class,levels=c("p","k"))) |> 
  pivot_longer(cols = starts_with("efeito_"),names_to = "resp_class",values_to = "resp_values") |> 
  mutate(resp_class = factor(resp_class,levels=names(df_contrastes)[4:6])) |> 
  ggplot(aes(x=pred_values,y=resp_values)) +
  geom_point(alpha=0.4) +
  geom_quantile(method="rqss",quantiles = c(0.05,0.5,0.95),lambda=0.1,color="darkred") +
  labs(title="Contrastes ~ p e k") +
  facet_grid(pred_class~resp_class,scales="free")
```

__figura 1__ Contrastes em função das preditoras


```{r intervalo de predição para os contrastes segundo estimado pelo GAMM}
df_plot <- df_intPred |> 
  mutate(p = p_z*sd(df_ad$p) + mean(df_ad$p),
         k = k_z*sd(df_ad$k) + mean(df_ad$k),
         name=factor(name,levels=paste0("efeito_",c("area","frag","conf")))) |> 
  select(-contains("_z"),-predito) |> 
  pivot_longer(starts_with("Q_0."),values_to = "pred",names_to = "label")
df_plot$label <- factor(df_plot$label,levels = unique(df_plot$label)[c(3,2,4,1,5)])
# gráficos
v_range <- range(df_plot$pred)
v_breaks1 <- c(-0.2,0,0.2,0.5,1)
f_plot <- function(df){
  f_ggplot <- function(df,facets=2){
  ggplot(df,aes(x=p,y=k,z=pred,fill=pred)) +
    geom_raster() +
    geom_contour(aes(z=pred),
                 size=0.5,color="darkblue",
                 breaks=v_breaks1) +
    geom_text_contour(aes(z=pred),
                      breaks=v_breaks1,
                      label.placer = label_placer_flattest()) +
    scale_fill_gradient2(low="green",
                         mid="red",
                         high="black",
                         midpoint = 0.5,
                         limits=v_range,
                         # round(seq(v_range[1],v_range[2],length.out = 5)[1:4],2)
                         breaks=v_breaks1) +
    scale_y_reverse() +
    theme_classic() +
    guides(fill = guide_colourbar(title = gsub("efeito_","",df$name[1]))) +
    coord_cartesian(expand = FALSE) +
    labs(fill=df$name[1]) +
    facet_wrap(~label,ncol = facets,scales="free")
  }
  l_p <- list()
  l_p[[1]] <- df |> 
    filter(label == "Q_0.5") |>
    f_ggplot() + labs(x="")
  l_p[[2]] <- df |> 
    filter(label != "Q_0.5") |>
    f_ggplot()
  ggpubr::ggarrange(plotlist = l_p,nrow=2, common.legend = TRUE, legend="top")
}
l_plot <- dlply(df_plot,"name",f_plot)
p <- grid.arrange(grobs=l_plot,ncol=3)
ggsave("apendices/analise_dados/figuras/FigFinal_contrastes.png",p,
       width = 13,
       height = 9)
```


__figura 2__ Intervalo de predição do GAMM para os contrastes, desconsiderando os efeitos parciais associados com o sítio de amostragem.


```{r códigos para rodar o intervalo de predicao a posteriori,eval=F,include=F}
df_intPred <- ldply(l_md.contrastes,f_PredInt.GAMM)
```



## Área per se

### gam e validação

```{r efeito area gam e validacao}
i <- "efeito_area"
md <- l_md.contrastes[[i]]
md
print("k.check:")
k.check(md)
print("summary:")
summary(md)
gratia::appraise(md)
gratia::draw(md)
```
```{r predito para dados originais,fig.height=18,fig.width=15}
df_plot <- cbind(md$model,
                 predict(md,se.fit=TRUE)) |> 
  inner_join(x=df_p,"SiteCode") |> 
  arrange(p) |> 
  mutate(label = paste0(SiteCode,", p=",round(p,2)))
df_plot$label <- factor(df_plot$label,levels=unique(df_plot$label))
df_plot |> 
  ggplot(aes(x=k_z,y=value)) +
  geom_line(aes(y=fit),color="darkred") +
  geom_line(aes(y=fit+se.fit)) +
  geom_line(aes(y=fit-se.fit)) +
  geom_point(alpha=0.5) +
  scale_x_reverse() +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  labs(title="Contraste Área",y="",subtitle="eixo x reverso") +
  facet_wrap(~label,ncol=4,scales="free") +
  theme(strip.text=element_text(margin=margin()),
        panel.spacing=unit(0, "lines"))
ggsave(paste0("apendices/analise_dados/figuras/",i,"_site_kGAMM.png"),
       width = 7,
       height = 30)  
```

## Frag per se

```{r efeito frag gam e validacao}
i <- "efeito_frag"
md <- l_md.contrastes[[i]]
md
print("k.check:")
k.check(md)
print("summary:")
summary(md)
gratia::appraise(md)
gratia::draw(md)
```
```{r efeito frag predito para dados originais,fig.height=18,fig.width=15}
df_plot <- cbind(md$model,
                 predict(md,se.fit=TRUE)) |> 
  inner_join(x=df_p,"SiteCode") |> 
  arrange(p) |> 
  mutate(label = paste0(SiteCode,", p=",round(p,2)))
df_plot$label <- factor(df_plot$label,levels=unique(df_plot$label))
df_plot |> 
  ggplot(aes(x=k_z,y=value)) +
  geom_hline(yintercept = 0) +
  geom_line(aes(y=fit),color="darkred") +
  geom_line(aes(y=fit+se.fit)) +
  geom_line(aes(y=fit-se.fit)) +
  geom_point(alpha=0.5) +
  scale_x_reverse() +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  labs(title="Contraste Frag",y="",subtitle="eixo x reverso") +
  facet_wrap(~label,ncol=4,scales="free") +
  theme(strip.text=element_text(margin=margin()),
        panel.spacing=unit(0, "lines"))
ggsave(paste0("apendices/analise_dados/figuras/",i,"_site_kGAMM.png"),
       width = 7,
       height = 30)
```


## Contemporâneo

```{r efeito conf gam e validacao}
i <- "efeito_conf"
md <- l_md.contrastes[[i]]
md
print("k.check:")
k.check(md)
print("summary:")
summary(md)
gratia::appraise(md)
gratia::draw(md)
```
```{r efeito conf predito para dados originais,fig.height=18,fig.width=15}
df_plot <- cbind(md$model,
                 predict(md,se.fit=TRUE)) |> 
  inner_join(x=df_p,"SiteCode") |> 
  arrange(p) |> 
  mutate(label = paste0(SiteCode,", p=",round(p,2)))
df_plot$label <- factor(df_plot$label,levels=unique(df_plot$label))
df_plot |> 
  ggplot(aes(x=k_z,y=value)) +
  geom_hline(yintercept = 0) +
  geom_line(aes(y=fit),color="darkred") +
  geom_line(aes(y=fit+se.fit)) +
  geom_line(aes(y=fit-se.fit)) +
  geom_point(alpha=0.5) +
  scale_x_reverse() +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  labs(title="Contraste Frag",y="",subtitle="eixo x reverso") +
  facet_wrap(~label,ncol=4,scales="free") +
  theme(strip.text=element_text(margin=margin()),
        panel.spacing=unit(0, "lines"))
ggsave(paste0("apendices/analise_dados/figuras/",i,"_site_kGAMM.png"),
       width = 7,
       height = 30)
```
