
## Materiais e Método

- Selecionamos na base de dados TreeCo inventários florestais que amostraram em parcela única pelo menos 1ha de floresta, com alta confiabilidade taxonômica dos indivíduos com DBH>=5.0cm e da coordenada central da parcela, totalizando 109 sítios (mediana da área da parcela é XX ha).  
- Usamos mapas de cobertura vegetal contemporâneos aos inventários florestais na base de dados REF XXXX. 
- Um desafio de implementar esses modelos é definir a extensão espacial da paisagem ao redor que deve fornecendo a maior parte dos propágulos para a parcela (Jackson & Fahrig 2015).

### determinação da extensão espacial da paisagem ao redor 
- A predição dos modelos espacialmente explícitos depende de uma extensão espacial mínima, que não seja muito pequena para restringir a construção da árvore genealógica na simulação coalescente (THOMPSON PACOTE R 2021). 
- Os modelos espacialmente implícitos e sem espaço dependem de uma extensão espacial ótima, englobando a maior parte das áreas que fornecem propágulos para a parcela.



Pressuposto a existência de uma resposta não linear da diversidade local e proporção de cobertura vegetal na paisagem (Jackson & Fahrig 2015), determinamos a extensão espacial da paisagem que maximiza o peso de evidência da relação entre a riqueza na parcela e um polinômio de segundo grau da proporção de cobertura vegetal; obtemos paisagens de 4x4 km2 (SI). 

Aproximamos a área da paisagem e a parcela por quadrados concêntricos, modificamos a resolução dos mapas para que a densidade de pixels seja igual à densidade de indivíduos na parcela e determinamos que pixels com cobertura vegetal a 70% são habitat e os demais matriz. Nos mapas de equilíbrio em paisagem idealizada íntegra só existe habitat. Os modelos neutros espacialmente explícitos usam uma simulação coalescente para reconstruir a árvore genealógica dos indivíduos na parcela e com isso é possível estimar a taxa de colonização de novas espécies na paisagem, taxa U, necessária para obter a riqueza de espécies na parcela e simular a distribuição de abundância dos indivíduos (SAD). Simulamos 20 cenários de limitação à dispersão, pressupomos que todos os indivíduos na paisagem se dispersam segundo uma i.i.d. distribuição de Laplace em dois eixos ortogonais (função de dispersão). Os modelos neutros que pressupõe apenas a quantidade de habitat remanescente (espacialmente implícitos) usam a fórmula de amostragem de Etienne (2005) para simular a SAD. Convertemos os 3 parâmetros dos modelos neutros espacialmente explícitos (configuração espacial do habitat, taxa U e desvio padrão da função de dispersão) para os 2 parâmetros dos respectivos modelos espacialmente implícitos (theta, relacionado com a diversidade na paisagem; e m, a probabilidade média de uma substituição na parcela ser por um propágulo de fora da parcela). Para cada sítio, cenário de limitação de dispersão e modelo neutro, simulamos 100 SADs. Comparamos as SADs preditas com a respectiva SAD observada usando uma versão do teste de Kolmogorov-Smirnov; consideramos que a SAD predita era congruente se o valor p do teste era superior à 0.05. Por modelo neutro, investigamos a probabilidade de congruência da SAD predita com a observada comparando GLMMs binomiais que incluíram a interação entre polinômios de segundo grau da proporção de cobertura vegetal e do desvio padrão da função de dispersão e também a ausência destas variáveis.