---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
# pacotes
library(trackdown)
# both overwrite: 
# overwrite the current google drive file with the current Rmd:
# upload_file(file="secoes_texto/Resultados/Resultados.Rmd",
#             gpath="mestrado/artigo_principal/secoes_texto/",
#             hide_code=TRUE)
update_file(file ="secoes_texto/Resultados/Resultados.Rmd",
            gpath = "mestrado/artigo_principal/secoes_texto/",
            hide_code = TRUE)
# overwrite the current Rmd with the current google drive 
download_file(file = "secoes_texto/Resultados/Resultados.Rmd",
              gpath = "mestrado/artigo_principal/secoes_texto/")
```

# Intodução

## Opening

Não há consenso entre os dois principais programas de pesquisa em ecologia de paisagem sobre o papel do espaço nas causas da perda de habitat (glossário[a]) na manutenção da diversidade local (glossário[b]; veja REFs). Optar por desconsiderar os efeitos das mudanças espaciais podem influenciar a seleção e desenho de paisagem para a conservação e restauração dos ecossistemas naturais (REFs). O programa que pressupõe independência dos efeitos da perda de habitat e da configuração espacial, controlado pela quantidade de habitat ( chamado de fragmentação per se), conclui que os efeitos da fragmentação per se são pequenos em comparação aos efeitos da perda de habitat e idiossincráticos, em sua maioria positivos, para a observação do número de espécies no habitat remanescente (REFs). 



O programa que pressupõe interdependência entre os efeitos da perda de habitat e as concomitantes mudanças na configuração espacial não reconhece a fragmentação per se enquanto padrão, e sim como resultado de um mesmo processo de transformação de habitat em matriz. Nessa perspectiva, é necessário considerar os efeitos indiretos da perda de habitat pela fragmentação per se

e sim a fragmentação de habitat como a perda de habitat e concomitante 
essas conclusões que pressupõem independência a priori entre quantidade de habitat e a chamada fragmentação per se; e conclui que, em adição aos efeitos negativos da perda de habitat, a fragmentação per se apresenta efeitos negativos na observação de números de espécies no habitat remanescente (REFs).

## Funnel
Um desafio em avaliar as hipóteses de cada programa de pesquisa em um arcabouço comum  são as métricas de perda de área e de fragmentação per se (REFs). A proporção de cobertura vegetal e as métricas de fragmentação per se covariam com a escala de observação, dado a configuração espacial do habitat na região estudada (REF). A escala de observação em geral é determinada pressupondo equilíbrio entre a diversidade local observada e a heterogeneidade da paisagem (glossário[c]) contemporânea à amostragem do local (REF). Na situação de equilíbrio a diversidade local flutua estocasticamente em torno de valores médios (REF). Modelos ecológicos de equilíbrio na heterogeneidade da paisagem sugerem que a conectividade da paisagem ao redor com a parcela é uma preditora necessária para descrever a diversidade local (REF). A conectividade, movimentação dos indivíduos no habitat remanescente, depende da configuração espacial do habitat remanescente e da capacidade de dispersão dos indivíduos (REF). Uma vez que a variabilidade na configuração espacial do habitat remanescente varia ao longo do gradiente de cobertura vegetal, uma expectativa é que os efeitos da perda de habitat e fragmentação per se variem com a proporção de cobertura vegetal (REF). Porém, alguns taxóns como árvores, podem apresentar longo atraso na resposta ecológica (glossário), muitas vezes maior do que a série histórica dos mapas de cobertura vegetal detalhados (REF). Assim, uma abordagem nula quanto aos efeitos da perda de habitat e fragmentação per se contemporâneos é que o equilíbrio foi atingidido em uma situação idealizada de ausência de perda de habitat (Fahrig et al. 2020).

########
O programa independentista conclui que os efeitos da fragmentação per se são pequenos em comparação aos efeitos da perda de haitat e idiossincráticos, em sua maioria positivos para a retenção de espécies no habitat remanescente (Fahrig et al.). Assim, 
O programa interdependetista não reconhece o conceito de fragmentação per se enquanto padrão, apenas fragmentação de habitat enquanto processo de perda de habitat e concomitante mudança na configuração espacial do habitat (REF). 
########

### Perguntas motivadoras
É suficiente desconsiderar a fragmentação per se para predizer a diversidade local de árvores? Uma expectativa do programa independente é que para modelar a diversidade local de árvores a partir de mapas de cobertura vegetal e dinâmicas ecológicas idealizadas é suficiente desconsiderar o isolamento estrutural informado pelo mapa de vegetal. Outra expectativa, que concilia a crítica do programa interdependentista, é que sob limitação de dispersão a particular configuração espacial do habitat pode restringir a movimentação dos indivíduos no habitat remanescente (conectitivade, REF). A restrição da conectividade pela configuração espacial pode variar ao longo do gradiente de cobertura vegetal, uma vez que a variabilidade nas possíveis configurações espaciais variam ao longo do gradiente de cobertura vegetal (REF). Os efeitos de área e de fragmentação per se na manutenção do número de espécies local, como idealizados pelo programa independente, podem ser estimados comparando adicionalmente a situação de ausência de perda de habitat. Como os efeito da fragmentação per se variam ao longo do gradiente de cobertura vegetal? Os efeitos de área e fragmentação per se diferem em magnitude? Desconsiderar o isolamento estrutural é suficiente mesmo quando o efeito estimado de fragmentação per se é elevado?



A diferença na situação de ausência de isolamento estrutural e ausência de perda de habitat, informa a redução no número de progenitores na paisagem, o efeito de perda de habitat.











## Objetivo[d]

Aqui comparamos a congruência do predito para a diversidade local de árvores por um modelo mínimo de dinâmica ecológica no equilíbrio (Campos et al. 2012,2013; Thompson et al. 2019) na configuração espacial contemporânea do habitat remanescente na paisagem ao redor (Villard & Metzger 2014; Frazier et al. 2017), com a situação de ausência de isolamento estrutural (REF), onde todo o habitat remanescente está aglomerado ao redor da parcela. A situação de ausência de perda de habitat na paisagem ao redor foi simulada como controle nulo (Fahrig et al. 2022). Para cada sítio de amostragem exploramos graus de limitação de dispersão per capita (Chisholm & Lichtenstein 2009?; Campos 2012,2013; Villard & Metzger 2014) e situação de ausência de limitação de dispersão entre os indivíduos da paisagem local (HAH Fahrig 2013; Saura e al. 2021)[e]. Se houver limitação de dispersão, o modelo prevê a possibilidade de que o isolamento estrutural da parcela na paisagem possa reduzir o input de espécies vindos da paisagem ao redor e/ou reduzir a erosão de espécies por deriva ecológica (glossário; veja Campos et al. 2012, 2013; Condit et al. 2012; May et al. 2012; Thompson et al. 2019). A taxa de colonização de novas espécies na paisagem por evento de nascimento (U, espacialmente aleatória na paisagem) foi ajustada para obter a riqueza observada localmente, dado o número de indivíduos na amostra. O contraste na taxa U estimada em cada tipo de paisagem pode informar o efeito da perda de habitat per se (contraste entre controle e sem isolamento estrutural) e do efeito da fragmentação per se (contraste entre sem isolamento estrutural e paisagem contemporânea) na manutenção da riqueza local. Esses contrastes informam a dependência de propágulos vindos da paisagem ao redor para repor espécies perdidas localmente e são condicionais à escala espacial da dinâmica ecológica simulada (REF). Nos perguntamos se negligenciar o efeito do isolamento estrutural contemporâneo é suficiente para predizer a distribuição de abundância de espécies (SAD) de árvores observadas em parcelas contíguas na Floresta Atlântica e como a chance relativa de congruência varia em função dos efeitos estimados de área e fragmentação per se ao longo do gradiente de cobertura vegetal observado e graus de limitação de dispersão simulados (Fletcher Jr et al. 2018; Fahrig et al. 2019; Editorial 2019; Watling et al. 2020; Pütkker et al. 2020). 

# Resumo do Método

Buscamos na base de dados TreeCo (Lima et al. 2015) inventários florestais que identificaram todos os indivíduos arbóreos com pelos menos 4.8 cm de DBH em parcela contíguas de pelo menos 1 ha na Floresta Atlântica. Selecionamos os inventários florestais com grande confiabilidade taxonômica e da coordenada central da parcela. Os inventários selecionados foram realizados entre 1986 e 2016, obtemos mapas  quadrados de cobertura vegetal do MapBiomas (coleção XX REF XX GREG) contemporâneos aos eventos de amostragem da SAD de 16 x 16 km2, pressupondo a data de publicação ou de coleta, quando disponível. A resolução dos mapas de cobertura vegetal foi ajustada por inventário, de modo que a densidade de pixels do mapa é igual à densidade de indivíduos na parcela. A parcela e a paisagem ao redor foram aproximadas por um quadrado. O modelo de equilíbrio é um modelo neutro espacialmente explícito (REFs) que simula as posições e distâncias de todos os indivíduos na paisagem pressupondo equilíbrio dinâmico na escala da paisagem, situação em que a taxa de perda de espécies devido à deriva ecológica é compensada pelo input de espécies descrito pela taxa U (REFs). Esse modelo neutro utiliza uma abordagem coalescente para reconstruir a árvore genealógica da comunidade amostrada na parcela, pressupondo equivalência funcional entre os indivíduos de diferentes espécies (REFs). Os graus de limitação de dispersão foram simulados com uma distribuição de Laplace controlando pela proporção de propágulos que permanece até o vizinho imediato do progenitor (k) variando de 0.99 até 0.05. Avaliamos o efeito da escala na estimativa U para buscar a extensão espacial da paisagem ao redor que acumulava a maior parte do efeito de aumentar a escala (apêndice Efeito de Escala). A extensão de 4x4 km2 foi suficiente para simular todos os 20 graus de limitação de dispersão e foi a exensão espacial usada para calcular a proporção de cobertura vegetal na paisagem ao redor (p). Simulamos 10 réplicas da taxa U e 100 réplicas da SAD para cada combinação de grau de limitação de dispersão e tipo de paisagem por inventário florestal. Os contrastes foram obtidos pela diferença das médias divido pela média no controle nulo, por grau de limitação de dispersão e inventário florestal. As SADs réplicas foram comparadas com a SAD observada usando a versão bootstrap do teste de Kolmogorov-Smirnov (REF); contabilizamos o número de réplicas com boa congruência (p-valor > 0.05, apêncide análise de dados). 

# Resultados

## Contrastes Estimados

</> Opening and the funnel <\>
A taxa U estimada para obter a riqueza observada no equilíbrio apresenta uma padrão canônico em paisagens sem perda de habitat (May et al. 2012), com um máximo em graus de limitação de dispersão intermediários (Figuras X). Quando a limitação de dispersão é severa a maior parte das substituições ocorre entre coespécificos, reduzindo a perda de espécies por deriva ecológica; com o relaxamento da limitação de dispersão para graus menos severos, há aumento na probabilidade de substituição de coespécificos; quando a limitação de dispersão é branda, subpopulações distantes na paisagem podem repor espécies perdidas localmente, reduzindo a taxa U necessária para redor as espécies perdidas localmente por deriva ecológica (May et al. 2012). A perda de habitat reduz o número de progenitores na paisagem, potencialmente reduzindo a oferta de propágulos para a parcela; e pode aumentar o isolamento estrutural reduzindo o input de propágulos vindos da paisagem ao redor para a parcela ou aumentando a probabilidade de substituição de coespecíficos. Se o isolamento estrutural majoritariamente reduz o input de propágulos vindos para a parcela, então a taxa U estimada na configuração contemporânea deve ser maior do que aquela estimada na ausência de isolamento estrutural. Se o isolamento estrutural majoritariamente aumenta a probabilidade de substituição de coespécificos, então a taxa U estimada na configuração contemporânea deve ser menor do que aquela estimada na ausência de isolamento estrutural. A forma do padrão canônico também depende do número de indivíduos e de espécies na parcela. Essas variáveis controlam o grau de exposição da árvore genealógica à paisagem ao redor, e.g., se o número de indivíduos é muito elevado em comparação ao número de espécies, há muitas linhagens iniciais para coalescerem em poucas linhagens finais (REFs, apêndice estimativa taxa U). 
<\> Resultados: Fatos e interpretação imediata (compreensão) <\>
- relação entre média e desvio padrão da estimativa da taxa U
- contrastes GE
- descrição estatística contrastes ~ p e k

## Chance relativa de congruência com a SAD observada

[a]perda de habitat: processo de transformação da área de ecossistemas naturais por área de atividades humanas não tradicionais (REF)
[b]diversidade local: a diversidade de características de diferentes espécies observados em uma determinada área. Devido à escassez de recursos para monitoramento, a maior parte das informações disponíveis são a identificação da espécies de indivíduos observados em uma amostra única no tempo; por exemplo, para árvores é comum delimitar parcelas em fragmentos florestais e identificar a espécie de todos os indivíduos a partir de um determinado DBH (REF)
[c]heterogeneidade da paisagem (Ben-Hur et al. 2020 Eco Let): pode ser decomposta em dois eixos. Composição: os tipos de áreas (e.g. habitat e não-habitat) ou o grau de uma variável ambiental.
Configuração: como a composição está distribuída espacialmente, considerando as posições e distâncias.
[d]A parte inicial me parece método. Acho que o parágrafo de objetivos deve ter perguntas, que devem estar auto-evidentes, a partir do que foi exposto nos parágrafos anteriores.
[e]faz sentido manter?
