---
title: "taxaU"
author: "Danilo Pereira Mori"
date: "2022-12-04"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,eval = FALSE,message = FALSE,warning = FALSE)
# pacotes
library(doMC)
library(patchwork)
library(gridExtra)
library(ggplot2)
library(readr)
library(purrr)
library(stringr)
library(tidyr)
library(insight)
library(bbmle)
library(DHARMa)
library(lme4)
library(plyr)
library(dplyr)
# objetos
# df_resultsMNEE
df_resultMNEE <- read_csv("dados/csv/resultados_MN/MNEE/cont/df_resultados.csv")
# df_sim
df_sim <- read_csv("dados/df_simulacao.csv") |> 
  select(-tif.path) |> 
  inner_join(
    mutate(
      data.frame(txt.path = list.files(path="dados/simulacao",pattern=".txt")),
      SiteCode = str_extract(txt.path,".*?(?=.txt)")),
    by = "SiteCode") |>  
  left_join(y=distinct(select(df_resultMNEE,p,SiteCode)),by="SiteCode")
# df_Urep
# df_Urep <- list.files(path="dados/csv/taxaU",pattern=".csv",full.names = T) |> 
#   map_df(~read_csv(.))
# write_csv(df_Urep,"dados/csv/df_Urep.csv")
df_Urep <- read_csv("dados/csv/df_Urep.csv")
df_U <- df_Urep |> 
  drop_na() |> 
  pivot_longer(cols = `1`:`10`,names_to = "n",values_to = "U") |> 
  group_by(SiteCode,k) |> 
  summarise(Umed = mean(U),
            Usd = sd(U),
            Umin = min(U),
            Umax = max(U)) |> 
  inner_join(x=select(df_sim,-txt.path,-d),by=c("SiteCode","k")) |> 
  inner_join(x=select(df_resultMNEE,p,SiteCode,k),by=c("SiteCode","k"))
# df_ad
```


## Gráficos Exploratórios da taxa U
__Umed ~ f(MN, p, k, Site)__

```{r fig 1 Umed ~ d +(SiteCode ~ p),eval=TRUE,fig.height=18,fig.width=15}
df_plot <- df_U |> 
  arrange(p) |> 
  # inner_join(mutate(data.frame(png.path = list.files(path = "dados/paisagens/png_land_sim",
  #                                             pattern=".png",full.names=T)),
  #                   SiteCode = str_extract(png.path,"(?<=im\\/).*?(?=\\.png)")),
  #            by = "SiteCode")
  mutate(label = paste0(SiteCode,", p=",round(p,2))) #, " ,S=",S_obs
df_plot$label <- factor(df_plot$label,levels=unique(df_plot$label))
# df_plot$label <- factor(df_plot$label,levels = unique(df_plot$label))
### essa função busca inserir o mapa de cobertura vegetal no gráfico de taxa U
# f_plot <- function(df){
#   img <- png::readPNG(df$png.path[1],native = T)
#   ggplot(df,aes(x=d,y=Umed)) +
#     inset_element(p=img) +
#     geom_point() +
#     geom_errorbar(aes(ymin=Umin,ymax=Umax)) +
#     geom_line() 
# }
# l_p <- dlply(df_plot,"SiteCode",f_plot)
# gráficos
df_plot |> 
  ggplot(aes(x=k,y=Umed)) +
  geom_smooth(method = "loess",se=F) +
  geom_point() +
  # labs(title="b) k, prop. propágulos até a vizinhança (~cut(p, 20))",
  #      y="número de SADs réplicas congruentes",
  #      x="k") +
  theme_bw() +
  scale_x_reverse() +
  facet_wrap(~label,ncol=4,scales="free")
ggsave("apendices/taxaU/figuras/Umed_kSite_loess.png",
       width = 7,
       height = 27.7)
```

__Figura 1__ Média da taxa U estimada pelo desvio padrão da função de dispersão, média de 10 réplicas. p = proporção de cobertura vegetal, S = riqueza de espécies.

Sítios para olhar:

```{r auditoria dos sítios que apresentam padrão adiverso}
v_sitios <- c("RScach4","PEalia","MGubera","MSdour","SPitir1","RSgaur","PRsapo","PRdiam3","RSfaxi","RSvsol","SPcara3","PRanto11","PRanto8","SPeec1","SPpecb1")
# v_missingSite <- v_sitios[!(v_sitios %in% df_plot$SiteCode)]
df_plot <- df_sim |> filter(SiteCode %in% v_sitios & k == 0.99)
f_landscape <- function(df){
  m <- as.matrix(read.table(paste0("dados/simulacao/",df$txt.path)))
  image(m,axes=F,main=paste0(df$SiteCode,", S=",df$S_obs,", p=",round(df$p,3)),zlim=c(0,2))
}
par(mar=c(0.2,0.2,2.2,0.2),mfrow=c(3,5))
a_ply(df_plot,1,f_landscape)
```

## Contrastes entre o estimado nos diferentes tipos de paisagem

```{r}
# preparação dos dados: incluir uma coluna de land type nos arquivos de 
# f_list.files <- \(path_file){
#   df <- read_csv(path_file) 
#   df_write <- inner_join(x=data.frame(SiteCode = df$SiteCode[1],land_type="contemp"),y=df,by="SiteCode")
#   write_csv(df_write,file = path_file)
# }
# a_ply(list.files(path="dados/csv/taxaU/MNEE/cont",pattern = ".csv",full.names = T),
#       1,
#       .fun = f_list.files)
# dados
df_Urep <- list.files(path = "dados/csv/taxaU/", pattern = ".csv",recursive = T,full.names = T) |> 
  map_df(~read_csv(.)) |> na.omit() #na.omit para remover o Sítio em que não foi possível rodar pela relação N / p
# sumarização
df_U <- df_Urep |> select(SiteCode:k)
df_U$Umed <- apply(select(df_Urep,-c(SiteCode:d)),1,mean)
df_U$Usd <- apply(select(df_Urep,-c(SiteCode:d)),1,sd)
df_contrastes <- df_U |>  
  pivot_wider(names_from = land_type, values_from = c(Umed,Usd)) 


```

```{r}
df_plot <- df_Urep |> select(-d) |> 
  pivot_longer(-c(SiteCode:k),names_to = "rep",values_to = "U") |>
  inner_join(x=unique(select(df_sim,SiteCode,p)),by="SiteCode") |> 
  arrange(p) |> 
  mutate(label = paste0(SiteCode,", p=",round(p,2)))
# df_plot <- df_U |>
#   inner_join(x=unique(select(df_sim,SiteCode,p)),by="SiteCode") |> 
#   arrange(p) |> 
#   mutate(label = paste0(SiteCode,", p=",round(p,2))) #, " ,S=",S_obs
df_plot$label <- factor(df_plot$label,levels=unique(df_plot$label))
df_plot |> 
  ggplot(aes(x=k,y=U,color=land_type)) +
  geom_point(alpha=0.1) +
  # geom_line() +
  stat_summary(geom = "line",fun.data = mean_se,alpha=0.5) +
  scale_x_reverse() +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  theme_bw() +
  labs(color="landscape type") +
  theme(legend.position = "top",
        axis.text=element_text(size=4.5),
        strip.text = element_text(size = 4.5, margin = margin())) +
  scale_color_manual(values=c("darkred","darkblue","darkgreen"),
                     labels=c("contemporâneo","idealizado","sem fragmentação")) +
  facet_wrap(~label,ncol=4,scales="free")
ggsave("apendices/taxaU/figuras/Umed_Usd_landType_Site.png",
       width = 7,
       height = 30)
```





### Códigos para estimativa da taxa U ainda em desenvolvimento - avaliar necessidade

```{r taxa U para SCarar - sitio com NAs quando Umin igual a 1.25e-06,include=F,eval=F}
setwd("dados/simulacao")
df <- filter(df_sim,SiteCode == "SCarar")
X_i <- df[1,]
f_taxaU2 <- function(df, n_replicas=10, Umin=1.25e-08, diminuir=5, parallel=TRUE, n_cores=3){
  f_simCoalescente <- function(X){
    v <- dinamica_coalescente(U = Umin, S=X$S_obs, disp_range = X$d, N_simul=1,landscape = X$txt.path, decay = diminuir)
    if(any(is.na(v))){
      return(NA)
    } else{
      return(v$U_est)
      }
  }
  f_write <- function(X_i){
    v_U <- replicate(n=n_replicas,f_simCoalescente(X = X_i))
    df_write <- cbind(select(X_i,SiteCode,k,d),
                        matrix(v_U,nrow=1))
    write_csv(df_write,file = paste0("../csv/taxaU/",X_i$SiteCode,"_k",round(X_i$k,2),".csv"))
  }
  registerDoMC(n_cores)
  a_ply(df,1,f_write,.parallel = TRUE)
}
f_taxaU2(filter(df_sim,SiteCode == "SCarar"))
```


