---
title: "Discussão"
output:
  bookdown::word_document2: default
  bookdown::pdf_document2:
    latex_engine: lualatex
  pdf_document: default
  html_document:
    df_print: paged
bibliography: /home/danilo/Documentos/mestrado_Ecologia/artigo_principal/1_to_compile_dissertacao_EM_USO/resources/citations2.bib
csl: "/home/danilo/Documentos/mestrado_Ecologia/artigo_principal/1_to_compile_dissertacao_EM_USO/resources/ecological-monographs.csl"
header-includes:
- \usepackage[brazil]{babel}
- \usepackage{lmodern}
- \usepackage{fontspec}
- \setmainfont{Times New Roman}
---

# Qual o significado dos achados ao debate sobre fragmentação de habitat?

<p>
Neste trabalho, buscamos desenvolver uma reconciliação empírica no debate sobre fragmentação de habitat por meio de três avanços interligados. 
</p>

<p>
Primeiro, observamos que o modelo mecanístico de primeira aproximação da conectividade (@riva_banskleite2024), o modelo neutro espacialmente explícito (MNEE), apresentou boa congruência com os padrões observados em paisagens reais (Fig. 7), sendo, portanto, válido como ferramenta de inferência. O MNEE teve boa previsão da distribuição de abundância de espécies (SAD) em 67 sítios da Floresta Atlântica (~64%), com bom desempenho na média entre os sítios. A congruência foi mantida mesmo sob gradientes extremos de cobertura florestal (~3–100%) e de dispersão (k = 0,5–0,99), demonstrando que processos neutros espacialmente condicionados podem explicar padrões de biodiversidade em paisagens reais (@Gilbert2006, @etienne_spatial_2011, @rosindell_case_2012, @leroi_neutral_2020).
</p>

<p>
Segundo, apresentamos estimativas mecanísticas e escalonadas dos propostos efeitos da paisagem (área per se, fragmentação per se, fragmentação total) usando o MNEE calibrado para reproduzir a riqueza observada, com a extensão espacial da paisagem ajustada à capacidade de dispersão (Figs. 4, 5, 6). Para fins analíticos, esses efeitos foram definidos como diferenças entre tipos de paisagens hipotéticas: fragmentação total corresponde a fragmentada – prístina; fragmentação per se, a fragmentada – aglomerada; e área per se, a aglomerada – prístina. Diferentemente de estudos correlacionais, nossa abordagem simula contrastes experimentais entre essas paisagens, controlando a escala espacial a cada cenário de dispersão (@jackson_are_2015,  @fahrig_ecological_2017, @fletcher2018habitat, @fahrig2019habitatA, @fletcher_jr_addressing_2023). 
</p>

<p>
Terceiro, utilizamos uma métrica funcional unificadora (logUi/Uj) para expressar os propostos efeitos da paisagem. A taxa U, tradicionalmente interpretada como 'taxa de especiação' em modelos neutros, ganha aqui um significado expandido. Ela encapsula a dependência da comunidade a processos de reposição de espécies (dispersão de longa distância, banco de propágulos ou especiação) e a eficiência da paisagem em mitigar perdas locais por deriva ecológica. O contraste logUi/Uj entre paisagens revela diferentes efeitos da paisagem. Um deles está na conectividade funcional, que diz respeito a como a configuração espacial do habitat afeta a movimentação de indivíduos. Outro efeito se observa na dinâmica de substituição, isto é, como a topografia do habitat altera a probabilidade de reposição por coespecíficos.
</p>

# Resumo dos achados

<p>
Em resumo, observamos que os propostos efeitos da paisagem sobre a métrica funcional (expressa pelo log da razão entre taxas U) variam em função da cobertura florestal e da capacidade de dispersão das espécies (@swift2010critical, @villard_beyond_2014), com implicações diretas para a manutenção
da biodiversidade local através da modificação da conectividade funcional e resiliência demográfica da paisagem. Os três efeitos propostos (área per se, fragmentação per se e fragmentação total) apresentam um padrão geral de intensificação com a redução da cobertura florestal, com forma distinta em função da capacidade de dispersão simulada. O efeito de área per se apresenta o padrão mais consistente entre inventários, com efeito negativo acentuado exceto em cenários intermediários de limitação de dispersão. Os efeitos de fragmentação per se e de fragmentação total apresentam mais inventários que distoam do padrão de cada efeito. O padrão geral do efeito de fragmentação per se é bifásico: positivo quando a limitação é severa e negativo quando branda. E o padrão geral do efeito de fragmentação total é de atenuação do efeito negativo com o aumento da limitação de dispersão. Os inventários que distoam, ocorrem em paisagens com alta cobertura florestal, onde os efeitos de fragmentação seguem o padrão bifásico da fragmentação per se. Em nossos achados (Figs. 11, 12, 13 ,14, 15) os efeitos seguem a relação fragmentação total = área per se + fragmentação per se. Observamos que com a redução da cobertura florestal o componente mais relevante da fragmentação total passa da fragmentação per se para a área per se, de tal forma que considerando todo o gradiente de cobertura florestal esses dois componentes possuem magnitudes similares. Porém, vale salientar, que nenhum dos efeitos propostos apresentam tamanho de efeito elevado, uma vez que não há mudança na ordem de magnitude da taxa U, não chegando a dobrar o valor da taxa U entre simulações. 
</p>

# Relação com os outros trabalhos que estimam os efeitos da paisagem na biodiversidade remanescente 

<p> 
Nossos resultados diferem dos estudos observacionais comparativos em um aspecto fundamental. Os estudos observacionais comparativos obtem estimativas de efeito pela comparação de diferentes inventários florestais (e.g. @fahrig_ecological_2017;  @puttker_indirect_2020; @watling2020support; e @gonccalves2025species). Em nossos resultados os efeitos são obtidos para um mesmo inventário pela comparação de diferentes simulações de como o dado observado foi gerado. As simulações nas paisagens hipotéticas podem ser interpretadas de três formas distintas. Na paisagem fragmentada a situação representada é de ausência de atraso na resposta da biodiversidade local em relação à configuração espacial da paisagem contemporânea ao inventário (@campos_neutral_2012, @campos_effect_2013, @claudino_extinction_2015, @thompson_characterising_2019). Na paisagem aglomerada é a situação em que a ausência de atraso na resposta ecológica é melhor aproximada quando todo o habitat remanescente na paisagem fragmentada está o mais próximo da parcela. Essa hipótese é similar à hipótese da quantidade de habitat (@fahrig_rethinking_2013), em que as distâncias impostas pela criação da matrix não interferem na movimentação dos indivíduos no habitat remanescente na paisagem. A paisagem prístina representa a situação de total atraso na resposta ecológica em relação a perda e fragmentação de cobertura florestal (@chisholm_speciesarea_2018; @thompson_characterising_2019, @fahrig_resolving_2022). Portanto, em nossos resultados o efeito da paisagem descreve o quanto a biodiversidade remanescente se torna mais ou menos vulnerável ao mudar de uma paisagem para a outra. O efeito de fragmentação total é o efeito de mudar da paisagem prístina para a paisagem fragmentada. O efeito de área per se é o de mudar da paisagem prístina para a aglomerada; e o de fragmentação per se, da aglomerada para a fragmentada. 
</p> 

<p> 
Dessa forma, os efeitos que obtemos representam como a paisagem influencia a manutenção da biodiversidade local em termos de conectividade e resiliência demográfica sob diferentes cenários, dado a observação de um único inventário. E então fazemos um sumário descritivo, agregando os efeitos para o conjunto de inventários selecionados, em função da porcentagem de cobertura florestal e capacidade de dispersão dos indivíduos investigados (@villard_beyond_2014; @fahrig_ecological_2017;  @watling2020support; e @gonccalves2025species). Nesse aspecto, nossos resultados tem a vantagem de controlar por características que variam entre inventários (@feller2015hierarchical), uma vez que para um mesmo inventário apenas a paisagem hipotética é modificada, o número de indivíduo, a área amostrada, o número de espécies e a quantidade de cobertura remanescente se mantém. Por outro lado, introduzimos o viés do modelo mecanístico, enquanto tornamos explicíto a incerteza entorno da capacidade de dispersão dos indivíduos em paisagens reais (\@ref(assumpMNEE)). Já um aspecto comum de nossos resultados com os de trabalhos observacionais comparativos é o pressuposto de contemporaneidade, que se associa as características contemporâneas da paisagem com o padrão de biodiversidade remanescente observado (@ref(assumpCont)). A seguir iremos discutir nossos achados com trabalhos observacionais comparativos que aplicam diferentes metodologias, mas são comparáveis uma vez que exploram os efeitos da paisagem na flora de ecossistemas florestais: @fahrig_ecological_2017;  @puttker_indirect_2020; e @watling2020support.
</p>

## Fahrig (2017)

<p>
Em revisão de evidências, @fahrig_ecological_2017 observou que a fragmentação per se tem efeitos majoritariamente positivos (76%) quando significativos, sendo muito menos impactante que a perda de habitat. Segundo @fahrig_ecological_2017, os efeitos positivos da fragmentação per se foram observados em uma ampla gama de contextos, incluindo aqueles com baixa quantidade de habitat remanescente e sob limitação de dispersão branda - contrariando as expectativas prévias. 
</p>

<p>
Nossos resultados são diretamente comparáveis com os de @fahrig_ecological_2017 uma vez que aplicamos a lógica de estimar efeitos independentes de fragmentação per se e área per se (@fahrig_effects_2003; @fahrig_is_2019). Para isso usamos o contraste com o simulado na paisagem aglomerada (@fahrig_resolving_2022). A paisagem aglomerada possui a mesma quantidade de cobertura florestal que a paisagem fragmentada e a mesma configuração espacial da paisagem prístina (@valente_toward_2023). Dessa forma, ao comparar a paisagem fragmentada com a paisagem aglomerada, a única diferença entre as paisagens é a configuração espacial. E ao comparar a paisagem aglomerada e prístina, a única diferença é a quantidade de habitat. Dessa forma, isolando os efeitos (@fahrig_resolving_2022). 
</p>

<p>
Nossos resultados convergem parcialmente com os achados por Fahrig (2017). Primeiro, observamos que o efeito de fragmentação per se são contexto-dependentes, variando entre positivo e negativo em diferentes inventários com cobertura florestal similar e para um mesmo inventário (Figs. 8-11), o que é consistente com o observado por Fahrig (2017). Essa variação é criticamente modulada pela capacidade de dispersão das espécies e a cobertura florestal – um fator não identificado por Fahrig (2017). Nós observamos efeitos positivos apenas sob severa limitação de dispersão, em alguns sítios com cobertura florestal elevada e de forma consistente em paisagens com pouca cobertura. (Figs. 11, 12, 13, 15). Segundo, os efeitos negativos foram observados quando a limitação de dispersão é branda, tornam-se mais frequentes, porém menos intensos, com a redução da cobertura florestal - contrariando as conclusões de Fahrig (2017). Portanto, observamos um padrão consistente do efeito bifásico da fragmentação per se modulado pela capacidade de dispersão. 
</p>

<p>
Segundo, em relação à diferença na magnitude absoluta dos efeitos de fragmentação per se e área per se, observamos que na maioria dos sítios analisados, há situações em que um efeito predomina sobre o outro. Se considerarmos todo o gradiente de cobertura florestal e cenários de limitação de dispersão, observamos que a diferença na magnitude dos efeitos é simetrica em torno do zero (fig. 14). Ao considerar a redução da cobertura florestal, a maior magnitude dos efeitos tende a se deslocar da fragmentação per se para a área per se, independentemente do grau de limitação de dispersão (fig. 15). Portanto, a partir de nossos achados é possível concluir que os efeitos de fragmentação per se e área per se podem variar em sua importância relativa para o efeito total da perda e fragmentação de cobertura florestal.
</p>

<p>
As discrepâncias entre nossos achados podem ser explicadas por alguns fatores. Aqui utilizamos uma métrica funcional unificada de efeito da paisagem que tem interpretação mecanística e é escalonada para a capacidade de dispersão simulada; enquanto que na revisão de Fahrig (2017) os trabalhos apresentam diversas métricas e escalas de análise. Outro ponto é que nossa análise descreve a variação dessa métrica funcional em função da cobertura florestal e capacidade de dispersão simnultaneamente. Enquanto em Fahrig (2017) as paisagens eram agrupadas e comparadas em relação a diferença na mediana, e não houve avaliação da interação entre cobertura florestal (quantidade e configuração) e capacidade de dispersão.
</p>

## @puttker_indirect_2020

<p>
No trabalho de @puttker_indirect_2020 um modelo de equações estruturais foi usado para estimar os efeitos diretos da perda de cobertura florestal e indiretos via mudança na configuração espacial na riqueza local de parcelas na (@didham_rethinking_2012). As principais conclusões de Pütkker et al. (2020) para a flora foram três. A primeira é que o efeito direto de perda de habitat é o principal fator para riqueza de espécies quando a paisagem apresenta pouca cobertura florestal (<30%). A segunda é que quando a cobertura florestal é elevada (>60%) os principais fatores relevantes para a riqueza local estão relacionados com a fragmentação: o efeito direto da fragmentação é negativo e o efeito indireto da área é positivo, pela redução da densidade de área de borda com o aumento da área de cobertura. A terceira foi de menor relevância dos propostos efeitos da paisagem quando a cobertura florestal é intermediária (entre 30% e 60%).
</p>

<p>
Nossos resultados convergem parcialmente com os resultados de @puttker_indirect_2020. Primeiro, também observamos que a magnitude e relevância do efeito de área per se é maior em paisagens com baixa cobertura florestal, esse padrão é mais claro sob severa limitação de dispersão, onde os efeitos de fragmentação per se e área per se apresentam sinais opostos. Nessas situações de severa limitação de dispersão em paisagens com pouca cobertura florestal, o efeito positivo de fragmentação per se atenua o efeito negativo da área per se, resultando em um efeito de fragmentação total negativo com menor magnitude (Figs. 11, 12, 14, 15). Segundo, também observamos inventários em paisagens com cobertura florestal elevada em que o efeito de fragmentação per se é o componente mais relevante. Nessas situações, observamos efeito positivo da fragmentação per se sob severa limitação de dispersão e efeito nulo da área per se. Nos achados de @puttker_indirect_2020 não há efeito positivo da fragmentação per se.
</p>

<p>

As discrepâncias entre nossos resultados pode ser explicado pelas diferenças metodológicas.
Primeiro, a métrica de efeito explorada no trabalho de @puttker_indirect_2020 se distingue da nossa por focar no número de espécies classificadas como especialistas. Enquanto nossos resultados abordam todos os indivíduos arbóreos na área da parcela. Para nossos resultados, pressupor todos os indivíduos arbóreos é fundamental, uma vez que modelamos explicitamente o efeito da competição por espaço (@azaele_statistical_2016).
</p>

<p>
Segundo, as estimativas de @puttker_indirect_2020 são desenhadas para distribuir a variância intercorrelacionada entre a perda de cobertura florestal e a métrica de fragmentação conforme a estrutura hierarquica pressuposto: a perda de cobertura florestal altera tanto a riqueza de espécies quanto a configuração espacial do habitat, assim como a configuração espacial altera a riqueza de espécies. Enquanto, que as nossas estimativas pressupõe independência dos efeitos (@fahrig_effects_2003, @@fahrig_ecological_2017; @fahrig_is_2019): a perda de habitat (a mudança da paisagem prístina para a aglomerada) ocorre de forma independente da fragmentação per se (a mudança da paisagem aglomerada para a fragmentada). Para representar a situação de variância intercorrelacionada entre o efeito de área per se e fragmentação per se, nosso modelo mecanístico baseado em indivíduos precisaria ser mais específico e simular as mudanças na paisagem prístina que resultaram na paisagem fragmentada (ver. @Marshall2014; @gianluca_ch4_2022;  @magliocca2023review). Nesse aspecto, nossos resultados se assemelham no efeito de fragmentação total, que no caso do @puttker_indirect_2020 é obtido pela soma do efeito direto da cobertura florestal e do efeito indireto via mudança na densidade de borda.
</p>

<p>
Terceiro, nossos resultados não explicitam o efeito de borda, apontado por @puttker_indirect_2020 como o principal fator associado com a fragmentação. Em uma futura formulação de MNEE é possível incluir o efeito de borda, enquanto uma região do habitat onde todos os indivíduos apresentam maior chance de morte e menor de reprodução (@thompson_pycoalescence_2020). Com a inclusão dessa nova paisagem hipotética seria possível avaliar o efeito da influência da matriz no habitat remanescente (efeito de borda), contrastando a paisagem fragmentada ou a paisagem prístina com a paisagem fragmentada com esse efeito de proximidade com a matriz. Contudo, tal como a capacidade de dispersão que não é conhecida a priori para cada situação, seria necessário investigar a sensibilidade da influência dos tipos de matriz no habitat remanescente em função de sua distância com o habitat remanescente. É preciso avaliar se a paisagem fragmentada com efeito de borda apresenta melhor congruência nos sítios em que MNEE nunca teve bom desempenho ou ampliar os cenários de limitação de dispersão com boa congruência (fig. 7). 
</p>

## @watling2020support

<p>
O trabalho de Watling et al. (2020) testou a hipótese da quantidade de habitat (@fahrig_rethinking_2013), em que se pressupõe dispersão ilimitada dentro da paisagem, de forma que a parcela é a uma amostra dos indivíduos presentes na paisagem. Esse tipo de hipótese pode ser representada por um modelo neutro espacialmente implícito que pressupõe probabilidade de imigração da paisagem para a parcela igual a 1 (@etienne2005new). Essa hipótese prediz que a principal preditora da riqueza local é a quantidade de habitat na escala da paisagem, enquanto métricas associadas com fragmentação per se ou medidas na escala do fragmento florestal (e.g. tamanho e isolamento do fragmento) não são relevantes (@fahrig_rethinking_2013). A análise de Watling et al. (2020) se baseia na comparação de modelos estatísticos que diferem em seu conjunto de variáveis, se a predição da hipótese estiver correta, então a única preditora plausível é a quantidade de habitat e métricas de fragmentação per se (e.g. densidade de fragmentos na paisagem) não devem ser relevantes. Assim, o trabalho de Watling et al. (2020) descreve os efeitos da paisagem, área per se e fragmentação per se, através da comparação da verossimilhança de modelos estatísticos. 
</p>

<p>
Watling et al. (2020) observou que um modelo que incluía apenas a quantidade de habitat foi, em média, mais de 40 vezes mais provável de fornecer o ajuste mais plausível aos dados de riqueza de espécies do que um modelo que também incluía a fragmentação per se. Nas raras vezes em que o efeito de fragmentação per se foi relevante, o efeito estimado foi positivo - essas situações foram observadas para a flora da Floresta Atlântica (@watling2020support). 
</p>

<p>
Nossos resultados convergem parcialmente com os resultados de Watling et al. (2020) para a flora da Floresta Atlântica. Também observamos relevância de ambos os efeitos de fragmentação per se e área per se, principalmente em paisagens com baixa cobertura florestal para os inventários florestais da Floresta Atlântica. Mas também observamos alguns casos em paisagens com cobertura florestal elevada. Esses resultados se Alinham com o observado para Watling et al. (2020) para o conjunto de dados da Floresta Atlântica, e dessa forma contraria a predição central da hipótese de quantidade de habitat, de que apenas a quantidade de habitat é relevante para compreender a biodiversidade local (@fahrig_rethinking_2013; @watling2020support). Por outro lado, observamos efeitos negativos da fragmentação per se nos cenários de limitação de dispersão branda. Se formos considerar o efeito agregado para todo o conjunto de dados, o efeito de fragmentação per se apresenta distribuição assimétrica ao redor do zero (figs. 12 e 14) - contrariando o observado por Watling et al. (2020). 
</p>

<p>
As discrepâncias em relação aos resultados de Watling et al. (2020) podem ser atribuídas a diferenças metodológicas. A estimativa desses efeitos por meio da interpretação direta dos coeficientes de modelos estatísticos que incluem métricas de quantidade de habitat e densidade de fragmentos - como feito por Watling et al. (2020) - e é alvo de debate pelo tipo de modelo usado e pela comparação métrica de fragmentação per se (@fletcher_jr_negative_2018; @fahrig_is_2019; @valente_toward_2023). Nossos métodos não dependem especificamente de alguma métrica de fragmentação per se (e.g. número de fragmentos ou densidade de borda) mas sim do contraste com uma paisagem alternativa considera sem efeito de fragmentação per se, a paisagem aglomerada.
</p>

# Limiar de cobertura florestal e os propostos efeitos da paisagem na predição da biodiversidade local

Os nossos achados revelam um padrão não linear dos propostos efeitos da paisagem ao longo do gradiente de cobertura florestal, modulados pela capacidade de dispersão (@swift2010critical; @villard_beyond_2014; @arroyo-rodriguez_designing_2020; @banks-leite_suggestion_2021; @arroyo-rodriguez_preserving_2021). Identificamos aumento da relevância dos efeitos da paisagem em paisagens com cobertura florestal abaixo de 60%. Nessas paisagens com baixa cobertura florestal, o efeito negativo de área per se domina, principalmente sob severa limitação de dispersão, onde o efeito de fragmentação per se apresenta  efeito positivo, mas o efeito de fragmentação total é negativo (Figs. 11, 15). Em paisagens com alta cobertura florestal, há alguns poucos inventários em que a estimativa dos efeitos foge do padrão de baixa relevância, onde o padrão bifásico da fragmentação per se domina: com efeito positivo sob severa limitação de dispersão e negativo com o relaxamento da dispersão (Figs. 11, 15).

# Diferentes culturas de pesquisa e modelos ecológicos para a conservação

<p>
Outro ponto em debate é sobre como estratégias de conservação devem incorporar a ideia de limiar de cobertura florestal e outros fatores que determinam o sucesso das estratégias de conservação da biodiversidade remanescente (@arroyo-rodriguez_designing_2020; @banks-leite_suggestion_2021; @arroyo-rodriguez_preserving_2021).
De um lado, @arroyo-rodriguez_designing_2020 defenderam diretrizes gerais de conservação, baseadas em extensão revisão de análises na escala da paisagem, inclusive nas conclusões de Fahrig (2017), Watling et al. (2020) e @puttker_indirect_2020. Segundo esses autores, a configuração espacial da paisagem teria pouca relevância desde que houvesse pelo menos 40% de cobertura florestal, dividida em um fragmento principal e elementos menores de conexão (corredores, pequenos fragmentos, etc) em uma matrix de alta qualidade. Essa proposta representa uma heurística aplicável em larga escala, com foco na quantidade total de habitat e em maximizar a fragmentação per se, tendo como base a ideia de limiar de cobertura florestal.
</p>

<p>
Por outro lado, @banks-leite_suggestion_2021 criticaram essa abordagem, argumentando que a atual capacidade técnica e científica permite o ajuste das diretrizes de conservação às especificidades ecológicas e das práticas de conservação de cada região. Para sustentar essa posição, os autores citaram o trabalho de @strassburg2019strategic, que utilizou um modelo ecológico espacialmente implícito para integrar a relação espécie-área a práticas de restauração e conservação. 
</p>

<p>
A resposta de @arroyo-rodriguez_preserving_2021 a essa crítica foi centrada na viabilidade prática: apontaram que, embora modelos mais específicos possam oferecer cenários mais otimizados, em grande parte das regiões tropicais - onde se concentram os maiores desafios da conservação - não há dados disponíveis ou poder computacional suficiente para aplicar tais abordagens de forma ampla e sistemática.
</p>

<p>
Os resultados aqui apresentados foram obtidos com um modelo ecológico que pode investigar a influência da dispersão, configuração espacial de habitat e efeito de borda (@thompson_pycoalescence_2020), e portanto, ainda mais complexo do que o utilizado por @strassburg2019strategic, e a partir do mesmo tipo de dado utilizado nas abordagens generalistas, como Watling et al. (2020). A abordagem de @strassburg2019strategic se baseia em uma análise de risco de extinção para cada espécie (r): $r = 1 - (x/A_0)^z$; onde $A_0$ é a área de habitat contemporâneo, x é a área de habitat para ser restaurada e z é um parâmetro ajustável. Ou seja, não considera explicitamente o efeito da competição entre espécies, da capacidade de dispersão ou da mudança na configuração espacial pela adição de habitat (@strassburg2019strategic), como avaliamos aqui com MNEE. 
</p>

<p>
Assim, entendemos que o MNEE tem potencial como ferramenta de inferência em situações reais de conservação, conciliando demandas de ambos grupos de pesquisa por modelos simples, que possam ser ajustados com os dados disponíveis, e incluídos em análises de multiplos critérios. Para consolidar essa proposta, futuros estudos poderiam avaliar a capacidade do MNEE em descrever múltiplos padrões simultaneamente,  como alfa, beta e gama diversidade (@campos_neutral_2012, @campos_effect_2013; @fahrig_resolving_2022; @gonccalves2025species). Além disso, novas simulações poderiam incorporar a influência da matriz e explorar cenários contrafactuais, como a melhoria da permeabilidade da matriz ou o aumento da cobertura florestal total (@thompson_pycoalescence_2020). A partir de um modelo mecanístico suficiente e comum pode ser possível avaliar a existência de heurísticas aplicáveis em larga escala e explorar cenários multicritérios específicos (@metzger2017best; @pereira2020developing; @bull2021).
</p>

# Ressalvas

## Pressuposto de contemporaneidade e extensão espacial da paisagem {#assumpCont}

<p>
Todas as análise discutidas até agora (@fahrig_ecological_2017; @puttker_indirect_2020; @watling2020support; @strassburg2019strategic ; @gonccalves2025species; e este trabalho), correlacionam padrões de biodiversidade com as características da paisagem amostrada, assumindo que tais características influenciaram os padrões de biodiversidade observados (@frazier_landscape_2017). Esse pressuposto de contemporaneidade implica a constância das características da paisagem relevantes para gerar os padrões de biodiversidade e a ausência de atrasos na resposta da biodiversidade remanescente (REF), sendo adotado quando os dados disponíveis são escassos e estáticos (@frazier_landscape_2017). Em geral, bases de dados que compilam estudos observacionais contêm apenas uma classificação genérica do grau de preservação da parcela amostrada, sem informações detalhadas sobre a paisagem ao redor (@de_lima_how_2015; @chase2019fragsad). Dessa forma, alguns estudos optam por estratificar os sítios com base no grau de preservação informado na base de dados (e.g., @fahrig_ecological_2017, @fahrig_SLOSS2020, @riva_disproportionately_2022). Em nossos achados a classe de perturbação do sítio e as coordenadas geográficas foram covariáveis do modelo mais plausível para descrever a congruência da distribuição de abundância de espécies (tab. 1). Apesar da média da congruência ser similar tanto entre paisagens hipotéticas quanto entre classes de perturbação (Fig. 7). Assim, um dos motivos para a baixa congruência em alguns sítios pode ser o atraso na resposta ecológica para a mudança na paisagem, uma vez que MNEE pressupõe a situação de equilíbrio.
</p>

<p>
O pressuposto de equilíbrio garante que o pressuposo de contemporaneidade é válido na simulação, uma vez que é corresponde a situação de manutenção da configuração espacial do habitat, capacidade de dispersão e taxa de introdução de novas espécies por tempo suficiente tal que todo os padrões de biodiversidade se estabilizam (@kuussaari_extinction_2009; @lira_temporal_2019; @figueiredo_understanding_2019; @thompson_characterising_2019; @fahrig_resolving_2022). Um exemplo de análise que usa esse pressuposto de contemporaneidade é a análise de escala de efeito (@jackson_are_2015; ). Nessa análise o objetivo é determinar a escala espacial de análise como aquela que maximiza o poder explicativo da métrica de paisagem na resposta ecológica usada (@jackson_are_2015; @fletcher_jr_addressing_2023). Assim, nessa análise há um vínculo forte entre a extensão espacial da paisagem estimada e o pressupostos de contemporaneidade, pois víncula tanto o padrão de biodiversidade amostrado com a configuração espacial contemporânea à amostragem. Em nossa análise da sensibilidade da extensão espacial da paisagem em função da capacidade de dispersão (figs. 2, 3, 4, 5, 6), o pressuposto de equilíbrio não possui um vínculo tão forte com o pressuposto de contemporaneidade, uma vez que a estimativa é feita na paisagem prístina, por outro lado utiliza a riqueza observada - tal como a análise de escala de efeito.
</p>

<p>
Nossa estimativa de escala foi baseada em um algoritmo que pressupõe a expectativa teórica de aumento extensão espacial da paisagem com o aumento da capacidade de dispersão (@rosindell2013universal?). É possível calcular um parâmetro composto que combina a taxa U, a área da parcela (A) e a capacidade de dispersão média (L), $AU/L^2$ (@rosindell2013universal). Essa métrica informa a razão entre a área da parcela e a área média das espécies em uma paisagem prístina (@rosindell2013universal). Dado uma área da parcela e uma taxa U, quanto maior a capacidade de dispersão, menor a razão entre a área da parcela e a área da paisagem ao redor que contêm as espécies observadas na parcela. Assim, a expectativa era que quanto menor a capacidade de dispersão menor a extensão da paisagem ao redor suficiente para simular MNEE sem que a extensão espacial interferisse. Porém, observamos divergências com essa expectativa, devido ao fato de que a taxa U livre para aproximar a riqueza de espécies varia com a capacidade de dispersão (figs. 3, 4, 5, 6). 
</p>

<p>
Em cenários de limitação de dispersão intermediários, não foi possível observar um padrão de redução da taxa U com o aumento da extensão espacial. O que foi observado foram padrões não-monotônicos de variação na taxa U com o aumento da extensão espacial. Nesse cenários de limitação de dispersão a taxa U é pouco sensível a variação na extensão espacial e apresenta um máximo na taxa U estimada em paisagens prístinas com 16 km de lado (Fig. 3), a maior extensão considerada em nosso trabalho. Quando a taxa U é muito elevada, a particular configuração espacial da paisagem se torna menos relevantes para a manutenção da biodiversidade local (@campos_neutral_2012, @campos_effect_2013). Isso ocorre uma vez que quanto maior a importância da entrada de novas espécies na paisagem, menor a relevância dos indivíduos adultos na paisagem. Nesses cenários de limitação de dispersão observamos a menor magnitude do efeito de área per se em paisagens baixa cobertura florestal (figs. 11, 12 e 15). Os outros cenários de limitação de dispersão apresentaram o padrão monotônico decrescente, de redução da taxa U com o aumento da extensão espacial.
</p>

<p>
Outro fato inesperado com relação à estimativa de escala, foi a possível relação não linear entre a capacidade de dispersão e a extensão espacial suficiente para a simulação de MNEE (figs. 4, 5, 6). Nossos resultados sugerem que em cenários de severa limitação de dispersão a extensão espacial que acumula a maior redução na taxa U é superior a extensão espacial quando a limitação de dispersão é pouco branda (comparar k>0.80 e 0.50<k<0.60, figs 4, 5, 6). Quando a limitação de dispersão é muito branda (k<0.45), observamos um padrão mais consistente de aumento da escala que acumula a maior parte da redução na taxa U com a redução da limitação de dispersão. Trabalhos que investigam a escala espacial usando a análise de escala de efeito, também não encontraram um padrão claro de aumento da extensão espacial com o aumento da capacidade de dispersão (@miguet2016determines). 
</p>

<p>
A definição da escala espacial é um passo essencial para a construção da paisagem aglomerada, pois determina a quantidade do habitat remanescente que será aglomerado ao redor da parcela, e portanto, a estimativa dos efeitos de fragmentação per se e área per se dependem fundamentalmente da escala de análise (@fahrig_effects_2003, @fahrig_ecological_2017; @fletcher_jr_is_2018; @fletcher_jr_addressing_2023; @fahrig_is_2019). Diferente do efeito de fragmentação total que pode ser obtido escolhendo uma escala que seja suficiente para simular a maior capacidade de dispersão. A dependência que a escala de análise impõe na determinação dos efeitos de fragmentação per se e área per se é um ponto central do debate entre @fletcher_jr_is_2018 e @fahrig2019habitatA. 
</p>

<p>
Dado o conhecido atraso ecológico, uma forma de relaxar o pressuposto de contemporaneidade em nosso anaĺise é interpretar o efeito de fragmentação total como uma estimativa de débito de extinção da biodiversidade local (@thompson_characterising_2019). Então seria possível usar a congruência com a SAD para determinar se MNEE aproxima melhor pressupondo equilíbrio na paisagem fragmentada (com débito de extinção negligenciável) ou na paisagem prístina (com muito débito de extinção). Contudo, uma forma mais direta de relaxar o pressuposto de contemporaneidade é possibilitar que a conectividade seja espaço-temporal (@martensen2017). Esse tipo de modelo de conectividade espaço-temporal pode ser usado junto com modelos que descrevem explicitamente os processos de mudança da cobertura do solo por um sistema socioecológico (@metzger2017best; @pereira2020developing; @bull2021; @magliocca2023review). Com isso se torna possível explorar cenários mais específicos de efeitos da paisagem que incluem a perturbação antrópica e a regeneração natural (@metzger2017best; @pereira2020developing; @bull2021; @magliocca2023review). 
</p>

## Pressupostos de MNEE {#assumpMNEE}

### Soma-zero

<p>
No contexto de paisagens fragmentadas três pressupostos de MNEE são potencialmente problemáticos: soma-zero e equivalência funcional. O pressupostos de soma-zero impõe na simulação que cada adulto morto é reposto por um novo adulto, seja descentende dos adultos da paisagem ou de uma nova espécie na paisagem. Esse pressuposto é justificável em paisagens totalmente preenchidas de habitat, com ecossistemas funcionais, porém em paisagens fragmentadas a maioria das espécies arboreas especialistas de ambiente florestal apresentam redução na produção de propágulos (@aguilar2019habitat). Assim, o pressuposto de soma-zero pode estar subestimando os propostos efeitos da paisagem principalmente em paisagens com pouca cobertura florestal. Se relaxado o pressuposto de soma-zero, uma expectativa é de aumento da taxa U necessária para manter a riqueza local, pois a contribuição de novas espécies estaria também relacionado com a contribuição de novos indivíduos. Nesse contexto, poderia ser adequado decompor a taxa U na contribuição de indivíduos de fora da paisagem, que deve decair com a distância do limite da paisagem, da contribuição de especiação verdadeira e do banco de propágulos. Contudo, vale notar duas características da predição de MNEE. Primeiro, que MNEE apresenta boa congruência com o padrão empírico observado em sítios ao longo de todo gradiente de cobertura florestal (Fig. 7). Segundo, que os efeitos estimados estão parcialmente alinhados com conclusões de ambos grupos de pesquisa enquanto relevam a novidade da modulação da capacidade de dispersão.
</p>

### Função de dispersão

<p>
O MNEE pressupõe que todos os indivíduos apresentam a mesma função de dispersão, enquanto que nos sistemas naturais há grande variabilidade entre espécies, com diversos modos de dispersão que podem dependem de espécies de outros níveis tróficos (@clark1999seed; @bullock_synthesis_2017), e entre indivíduos de uma mesma espécie (REF). Uma expectativa é a diminuição da capacidade de dispersão de espécies especialistas de ecossistemas florestais, pela remoção de dispersores (REF), e o aumento da capacidade de dispersão de espécies generalistas (@bello2015defaunation). Uma vez que as informações sobre a capacidade de dispersão são escassos, a primeira aproximação de considerar uma mesma função de dispersão é justificada. A sensibilidade de nossos achados em relação ao tipo de distribuição de probabilidade usada na função de dispersão é um aspecto que precisa ser avaliado em futuros trabalhos. Aqui utilizamos uma função de dispersão exponencial. Em comparação de uma distribuição gaussiana e fat-tailed, @rosindell2013universal encontraram que quanto menor a escala da simulação, métrica que depende da área da parcela e da capacidade dispersão dos indivíduos, menor a diferença entre o tipo de função de dispersão. Em nossos resultados, exploramos parcelas com cerca de 1 ha de área e cenários de dispersão em que a maior dos propágulos permanece na vizinhança imediata da progenitora  (Figs. 1, 10, 11).
</p>

### Equivalência funcional e o programa de pesquisa da TNB

<p>
O outro pressuposto é a equivalência funcional, que impõe na simulação que todos as espécies tem as mesmas taxas de nascimento, morte e especiação. Nesse contexto, uma expectativa em relação a congruência geral de MNEE era de baixa congruência com a SAD observada em paisagens fragmentadas, uma vez que um modelo neutro espacialmente implícito (MNEI) de dinâmica temporal não apresentou boa congruência com a trajetória da abundância relativa de espécies em fragmentos experimentais (@Gilbert2006). Um MNEI compartilha o pressuposto de equivalência funcional com MNEE, mas difere em como o espaço se relaciona com a dinâmica demográfica das espécies: em MNEI a limitação de dispersão existe apenas entre a parcela e a paisagem ao redor (@etienne_spatial_2011; @azaele_statistical_2016). Nesses fragmentos experimentais algumas espécies tendem ao aumento da abundância enquanto outras à redução, o que contraria o pressuposto de equivalência funcional (@laurance2008theory). Por outro lado, a SAD é um padrão de biodiversidade que contém menos informação em relação à série histórica, uma vez que é um retrato momentâneo da biodiversidade remanescente. Para descrever a SAD, um MNEI é preferido em relação a um modelo com os mesmo pressupostos auxiliares mas com hierarquia competitiva entre espécies, uma vez que pode aproximar a SAD tão bem quanto, mas com menos parâmetros (@chisholm_niche_2010; @hammal_when_2015). Modelos neutros espacialmente implícitos (MNEI) apresentam boa congruência com a SAD observada, uma vez que os parâmetros desse modelo são livres para ajustar a SAD (@gotelli_null_2006; @rosindell_case_2012). Uma comparação de MNEE com MNEI havia concluído que dificilmente MNEE iria ter boa congruência com a SAD observada, pois o campo de parâmetros em que MNEE simulava a SAD era pouco coerente com o campo de parâmetros de MNEI que apresentava boa congruência com a SAD (@etienne_spatial_2011). Aqui em nossos resultados com um MNEE para descrever a SAD, apenas a taxa U foi livre para aproximar a riqueza observada, enquanto exploramos a sensibilidade da escala espacial quanto a variação na limitação de dispersão (Fig. 3 e 6). E observamos boa congruência sempre (variando a paisagem hipotética e a capacidade de dispersão per capita) em mais da metade dos sítios e boa congruência em média para todos os sítios (fig. 7).
</p>

<p>
O relaxamento do pressupostos de equivalência funcional pode ter efeitos não óbvios na taxa U e portanto em nossa estimativa de efeito da paisagem. Pode ser que ocorra redução na taxa U necessária para manter a riqueza, uma vez que processos estabilizadores podem sustentar uma população de uma espécie por tempo indeterminado (@adler2007niche; @hart2017spatial). Por outro lado a exclusão competitiva pode remover espécies que seriam mantidas no sistema caso a estocasticidade demográfica fosse mais relevante do que a hierarquia competitiva (@tilman2004niche; @rosindell_case_2012). Uma expectativa é que a diferença entre espécies seja maior quando há efeito de borda mais extremo, uma vez que isso criaria novos gradientes ambientais possivelmente favorecendo algumas espécie e prejudicando outras (@laurance2008theory; @schwartz2019fragmentation; @melito2018landscape). Tal como a capacidade de dispersão das espécies e o efeito de borda, a particular hierarquia competitiva de uma paisagem em geral não é conhecido, e poderia ser explorada multiplos cenários no qual a equivalência funcional é um deles.
</p>

<p>
O pressuposto de equivalência funcional é central dentro do programa de pesquisa da da Teoria Neutra da Biodiversidade (TNB). É possível dizer que TNB opera sob dois eixos conceituais no qual a construção de modelos é feita: a manutenção ou não do pressuposto de equivalência funcional ou dos pressupostos auxiliaires (e.g. soma-zero, a função de disperão e a paisagem). Quando um modelo neutro falha em predizer padrões observados de biodiversidade, é possível revisitar os pressupostos auxiliares ou o próprio pressuposto de equivalência funcional, aproximando-se de modelos de nicho que consideram hierarquias competitivas entre indivíduos de uma mesma guilda (@rosindell_case_2012; @leroi_neutral_2020). No entanto, não é raro que modelos neutros apresentem boa congruência com padrões empíricos amplamente utilizados no debate sobre fragmentação de habitat, como riqueza local e a distribuição de abundância de espécies (SAD), especialmente quando o mesmo padrão é usado tanto para calibrar quanto para validar a prediçao do modelo (@gotelli_null_2006; @rosindell_case_2012; @leroi_neutral_2020). Essa congruência pode ser interpretada como ponto de partida para expandir a capacidade preditiva do modelo: por exemplo, incluindo novos padrões, como a distribuição de biomassa, ou explorando cenários hipotéticos mais detalhados, como o efeito de borda e a variação na qualidade da matriz (@mcgill2007species; @metzger2017best; @thompson_pycoalescence_2020).
</p>

# Conclusão

<p>
Nossas estimativas mecanicistas dos efeitos propostos da paisagem sugerem que a discrepância entre as conclusões dos grupos de pesquisa em debate pode decorrer da ausência de considerações sobre a influência da capacidade de dispersão das espécies e da variabilidade inerente a cada sítio amostrado. Nos trabalhos observacionais comparativos as estimativas de efeitos são feitas a partir do conjunto de sítios selecionados, enquanto, em nosso conjunto de dados elas são obtidas para cada sítio enquanto avaliamos a sensibilidade dos resultados à incerteza na capacidade de dispersão dos indivíduos em paisagens reais. Permitindo explorar os efeitos da paisagem em cada caso específico usando dados limitados.
</p>

<p>
Por um lado é possível interpretar o debate sobre fragmentação de habitat enquanto a defesa da hipótese da decomposição ortogonal do efeito de fragmentação total em efeito de fragmentação per se e área per se (@fahrig_effects_2003, @fahrig2019habitatA; @didham_rethinking_2012; @fletcher_jr_negative_2018; @fahrig_is_2019). Nosso método não tem a capacidade de avaliar essa hipótese (ver @puttker_indirect_2020). O argumento por trás desse método que testa essa hipótese é de que uma vez que o habitat está distribuído no espaço, ao passo que se remove habitat, o espaço é modificado - um aspecto reconhecido por ambos os grupos em debate (@fahrig_effects_2003, @fahrig2019habitatA; @didham_rethinking_2012; @fletcher_jr_negative_2018; @fahrig_is_2019). Dentro desse método, a hipótese de independência dos efeitos de fragmentação total e área per se é um caso particular da situação geral de interdependência dos efeitos (@pearl2016causal). Por outro lado, a validade das estimativas de efeitos causais de @puttker_indirect_2020 dependem de que não existam efeitos da biodiversidade remanescente nas métricas da paisagem (@didham_rethinking_2012; @pearl2016causal). Esse pressupostos não deve ser válido para sistema florestais em que a restauração natural modifica a cobertura florestal e sua configuração espacial (@crouzeilles2020achieving; @williams2024global). Nesse contexto, uma forma de encaminhar o debate sobre os efeitos da fragmentação de habitat no habitat remanescente possa ser a exploração de cenários de mudanças da paisagem ao longo da história profunda e recente dos ecossistemas florestais. O modelo mecanístico consensual suficiente para explicar a trajetória desses ecossistemas florestais poderia ser usado como dispositivo de criação de contrafactuais para comparação de diferentes cenários de restauração e conservação e para criação de heurísticas gerais (@metzger2017best; @pereira2020developing; @bull2021; @arroyo-rodriguez_designing_2020; @banks-leite_suggestion_2021; @arroyo-rodriguez_preserving_2021).
</p>

# Referências