---
title: "Simulacoes"
author: "Mori, Danilo"
date: "18/03/2023"
output: 
  html_document:
    toc: true
    toc_depth: 5
editor_options: 
  chunk_output_type: console
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,eval = FALSE,message = FALSE,warning = FALSE)
# funções (deixar sempre em cima pois alguns carregam suas próprias bibliotecas)
source("source/dinamica_coalescente.R")
source("source/mapa_p_MNEE.R")
# pacotes
library(doMC)
library(gridExtra)
library(ggplot2)
library(readr)
library(purrr)
library(stringr)
library(tidyr)
library(plyr)
library(dplyr)
## dados comuns
# df_p
df_p <- read_csv("dados/df_p.csv")
#df_sítios simuláveis em MNEE contemporâneo
v_site <- read_csv("dados/csv/resultados_MN/MNEE/cont/df_resultados.csv") |> 
  pull(SiteCode) |> unique()
# df_sim
df_sim <- read_csv("dados/df_simulacao.csv") |> 
  dplyr::select(-tif.path) |> 
  inner_join(y=mutate(
    data.frame(txt.path = list.files(path="dados/simulacao",pattern=".txt")),
    SiteCode = str_extract(txt.path,".*?(?=.txt)")),
    by="SiteCode") |> 
  filter(SiteCode %in% v_site) |>
  left_join(df_p,by="SiteCode")
# df_sim <- cbind(df_sim,land_type = rep(x=c("ideal","non_frag"),each=nrow(df_sim)))
#
# df_simSAD <- inner_join(
#   df_sim %>% filter(land_type=="ideal") %>% select(-land_type),
#   read_csv("dados/csv/taxaU/df_U.csv") %>% filter(land_type!="ideal")
#   ) %>% select(-Usd)
#
df_SoE <- read_csv("./dados/csv/df_plotSoE.csv") %>% 
  select(k,SoE_0.95) %>% distinct() %>% 
  rename(SoE=2) %>% 
  mutate(SoE=ifelse(is.na(SoE),1,SoE))
#
df_sim <- inner_join(
  df_sim,
  df_SoE
)
# setwd("../..")
```


## Simulação

```{r função para simular as SADs para MNEE em diferentes tipos de paisagens}
setwd("dados/simulacao")
df <- df_sim %>% filter(SiteCode=="SPigua1")
registerDoMC(3)
v_gpath <- ".."
formals(f_simMNEE)$general_path <- v_gpath
#
# df_sim2 <- filter(df_sim,!SiteCode%in%df_lf$SiteCode)
df_sim2 <- filter(df_sim,SiteCode%in%vsite)
# f_d_ply <- function(dataframe) f_simMNEE(df = dataframe,general_path = v_gpath)
df <- df_sim2 %>% filter(SiteCode==vsite[2])
d_ply(df_sim2,"SiteCode",f_simMNEE,.parallel = TRUE)
```


## Teste KS

```{r teste KS}
setwd("../..")
df_SADrep <- mutate(
  data.frame(
    SADrep.path = list.files(path = "dados/csv_SoE/SADs_neutras/MNEE",
                             pattern = ".csv",
                             full.names = T,
                             recursive = T)
    ),
  SiteCode = str_extract(SADrep.path,
                         "(?<=[cont|frag|ideal]\\/).*?(?=_So)"),
  land_type = str_extract(SADrep.path,
                          "(?<=MNEE\\/).*?(?=\\/)"),
  SoE = str_extract(gsub("dados/csv_SoE","",SADrep.path),
                    "(?<=SoE).*?(?=km)"),
  SADobs.path = paste0("dados/csv/SADs_observadas/",SiteCode,".csv")
)
##################################################################
############## Existem sítios sem simulação? #####################
##################################################################
# em simulação?
resp <- FALSE
if(resp){
  vsite <- df_SADrep %>%
    group_by(SiteCode,land_type) %>%
    tally() %>%
    filter(n!=3) %>%
    pull(SiteCode)
  df_SADrep %>% filter(SiteCode%in%vsite,land_type=="ideal")
}
##################################################################
#
# função que une os data frames de diferentes escaslas em um só e aplica o teste KS
f_bySite_e_Land <- \(dfi,fname = "f_resultsMN",colname="SADrep.path"){
  #
  l_csv <- lapply(dfi[[colname]],read_csv)
  names(l_csv) <- dfi$SoE
  #
  df_sad <- do.call("rbind",l_csv)
  temppath <- tempfile(fileext = ".csv")
  write_csv(df_sad,temppath)
  #
  dfi <- select(dfi,-SoE) %>% 
    mutate(SADrep.path=temppath) %>% 
    distinct()
  f_dfi <- get(fname)
  dfr <- f_dfi(dfi)
  #
  file.remove(temppath)
  #
  return(dfr)
}
registerDoMC(2)
df_KSrep <- ddply(df_SADrep,
                  c("SiteCode","land_type"),
                  f_bySite_e_Land,
                  .parallel = TRUE)
write_csv(df_KSrep,file="dados/csv_SoE/df_KSrep.csv")
```

## Sumário dos resultados do teste KS

```{r sumarização dos resultados do teste KS}
f_summarise_SAD_MNEE <- \(df){
#@ df: df por site, k, e  land_type
#@ e.g. ddply(.,c("SiteCode","k","land_type"))
 cbind(df[1,c("SiteCode","k","land_type")],with(df,data.frame(
   nCongKS = sum(p.KS>0.05),
   Smed = mean(S),
   Ssd = sd(S),
   Smin = min(S),
   Smax = max(S)))
  )
}
df_KSrep <- read_csv(file="dados/csv_SoE/df_KSrep.csv")
registerDoMC(3)
df_ad <- ddply(df_KSrep,c("SiteCode","k","land_type"),
               f_summarise_SAD_MNEE,
               .parallel = TRUE)
write_csv(df_ad,file="dados/csv_SoE/df_congruencia_simulacao.csv")
```


## Contraste logU/U

```{r Contraste logU/U}
# dados
df_Urep <- mutate(
  data.frame(
    Urep.path = list.files(path = "dados/csv_SoE/taxaU/MNEE",
                           pattern = ".csv",
                           full.names = T,
                           recursive = T)
    ),
  SiteCode = str_extract(Urep.path,
                         "(?<=[cont|frag|ideal]\\/).*?(?=_So)"),
  land_type = str_extract(Urep.path,
                          "(?<=MNEE\\/).*?(?=\\/)"),
  SoE = str_extract(gsub("dados/csv_SoE","",Urep.path),
                    "(?<=SoE).*?(?=km)")
)
# função para unir as bases de dados de diferentes SoE
f_bySite_e_Land <- \(dfi,
                     colname="Urep.path"){
  l_csv <- lapply(dfi[[colname]],read_csv)
  do.call("rbind",l_csv)
}
registerDoMC(3)
df_Urep <- ddply(df_Urep,c("SiteCode","land_type"),f_bySite_e_Land,.parallel = TRUE)
df_Urep <- relocate(df_Urep,SiteCode)
# sumarização
source("source/2samples_testes.R")
formals(f_contraste_Umed)$path_U <- "dados/csv_SoE/taxaU/df_U.csv"
formals(f_contraste_Umed)$path_land_effect <- "dados/csv_SoE/taxaU/df_contrastes.csv"
f_contraste_Umed(df_Urep) # em 2samples_testes.R
```


## Sumário paisagens hipotéticas


## Contraste SAD


```{r}
f_z <- function(x) (x-mean(x))/sd(x)
source("source/dinamica_coalescente.R")
source("source/2samples_testes.R")
v_pares <- c("cont-ideal","non_frag-ideal","cont-non_frag")
# Resultados
## congruência 
df_ad <- read_csv(file="dados/csv_SoE/df_congruencia_simulacao.csv") %>% 
  rename(nSAD = nCongKS)
## efeito U
df_contrastes <- read_csv(file="dados/csv_SoE/taxaU/df_contrastes.csv")
## dados disponíveis
df_dados_disponiveis <- read_csv(file = "dados/df_dados_disponiveis.csv") %>% 
  select(SiteCode,year_bestProxy,forest_succession,matches("(lat|long)")) %>% 
  mutate(lat = ifelse(is.na(lat_correct),lat,lat_correct),
         long = ifelse(is.na(long_correct),long,long_correct),
         data_year = as.numeric(year_bestProxy),
         data_year = ifelse(is.na(data_year),2012.5,data_year)) %>% 
  select(-contains("correct"),-year_bestProxy)
# dados para modelos
# df_md0 <- df_adSAD %>%
#   filter(taxaU=="contemp",land_type=="contemp") %>%
#   select(SiteCode,k,nCongKS) %>%
#   inner_join(df_contrastes %>% select(SiteCode:k,frag.total_logratio)) # versão do
df_contrastes <- df_contrastes %>%
  select(SiteCode:p, contains("_logratio")) %>% 
  mutate(across(-SiteCode,f_z,.names = "{.col}_z")) %>% 
  select(SiteCode,k,p,k_z:frag.total_logratio_z) %>% 
  rename_with(~str_remove(.,"_logratio_z")) %>% 
  pivot_longer(cols = c("area","frag.perse","frag.total"),
               values_to = "Uefeito",
               names_to = "contraste") %>% 
  mutate(contraste = case_when(contraste=="area" ~ "non_frag-ideal",
                               contraste=="frag.total" ~ "cont-ideal",
                               contraste=="frag.perse" ~ "cont-non_frag"))
# df SADs congruentes
# df_adSADifself <- adply(c("contemp","ideal","non_frag"),1,\(i){
#   df_return <- df_adSAD %>% filter(taxaU==i & land_type==i) %>% 
#     select(-land_type,-c(Smed:Smax)) %>% 
#     rename("contrafactual"="taxaU",
#            "nCong"="nCongKS")
#   inner_join(df_return,
#              df_contrastes %>% 
#                filter(contraste=="non_frag-ideal") %>% 
#                select(SiteCode:p,ends_with("_z")),
#              by=c("SiteCode","k"))
# },.id=NULL)
# df_logOR para modelar
df_logOR <- df_ad %>% 
  f_prep_contrasteSAD(.,dfUefeito=df_contrastes) %>% 
  f_contrasteSAD(.,pares=v_pares) %>% 
  inner_join(y=df_contrastes,by=c("contraste","SiteCode","k")) %>% 
  inner_join(y=df_dados_disponiveis,by="SiteCode") %>% 
  relocate(p,.after=k)
write_csv(df_logOR,file="dados/csv/df_logOR.csv")
```

