---
title: "Documentos para 2o Comitê"
author: "Mori, Danilo"
date: "19/11/2022"
output: 
  bookdown::pdf_document2:
    latex_engine: xelatex
    fig_caption: yes
  bookdown::html_document2:
    toc: true
    toc_depth: 5
    fig_caption: yes
editor_options: 
  chunk_output_type: console
bibliography: ["/home/danilopereiramori/Documents/artigo_principal/to_compile_dissertacao/resources/citations.bib"]
csl: "/home/danilopereiramori/Documents/artigo_principal/to_compile_dissertacao/resources//plos.csl"
---

<style>
body {
text-align: justify}
</style>

# Materiais e Método 
```{r MeM, child='./to_compile_dissertacao/01_MeM/MaterialeMetodo.Rmd'}
```

# Resultados
```{r Resultados, child='./to_compile_dissertacao/02_Resultados/Resultados.Rmd'}
```

# Efeito de escala na estimativa da taxa U necessária para manter a riqueza local no equilíbrio em um modelo neutro espacialmente explícito
```{r Efeito de Escalar, child='./to_compile_dissertacao/03_EfeitoEscala/EfeitoEscala.Rmd'}
```

# Support Information

```{r SI, child='./to_compile_dissertacao/04_SI/SI.Rmd'}
```


